### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Clemdu63** [Torantulino/Auto-GPT#1090]
When I try to launch it with the command `python scripts/main.py` this error appears :

```
clementreviron@MacBook-Pro Auto-GPT % python scripts/main.py
Traceback (most recent call last):
  File "/Users/clementreviron/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/Users/clementreviron/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/Users/clementreviron/Auto-GPT/scripts/browse.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

How can I fix it ?

**Comment by Fnck** [comment]
may be you can run 'pip install requests' and re-run, reference:
https://pypi.org/project/requests/

**Comment by ethanolle** [comment]
`pip install -r requirements.txt`
please be sure to install all the packages.

**Comment by Clemdu63** [comment]
> `pip install -r requirements.txt`
> please be sure to install all the packages.

Of course I did but it still ask me to re-install every requirements one by one... I don't understand why and when I try to do the command again I got `Requirement already satisfied` so ... But now I'm block because I got `ModuleNotFoundError: No module named 'googleapiclient'` and I don't know how to install it...

**Comment by Clemdu63** [comment]
I already did it of course but I don't know why it asked me to reinstall everything one by one so I did it and now it works...

**Comment by muhammadahmedzahid** [comment]
I think this issue has been resolved we can close this issue.

**Comment by EmilyCheoh** [comment]
I ran into the same issue. I have all the dependencies downloades but it still says i don't have the 'requests' module. 

> emilyqiao@Emikos-Air Auto-GPT % pip install -r requirements.txt
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.11.1)
> Requirement already satisfied: colorama==0.4.6 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 2)) (0.4.6)
> Requirement already satisfied: openai==0.27.2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 3)) (0.27.2)
> Requirement already satisfied: playsound==1.2.2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 4)) (1.2.2)
> Requirement already satisfied: python-dotenv==1.0.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 5)) (1.0.0)
> Requirement already satisfied: pyyaml==6.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 6)) (6.0)
> Requirement already satisfied: readability-lxml==0.8.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 7)) (0.8.1)
> Requirement already satisfied: requests in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 8)) (2.28.2)
> Requirement already satisfied: tiktoken==0.3.3 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 9)) (0.3.3)
> Requirement already satisfied: gTTS==2.3.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 10)) (2.3.1)
> Requirement already satisfied: docker in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 11)) (6.0.1)
> Requirement already satisfied: duckduckgo-search in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 12)) (2.8.5)
> Requirement already satisfied: google-api-python-client in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 13)) (2.85.0)
> Requirement already satisfied: pinecone-client==2.2.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 14)) (2.2.1)
> Requirement already satisfied: redis in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 15)) (4.5.4)
> Requirement already satisfied: orjson in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 16)) (3.8.10)
> Requirement already satisfied: Pillow in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 17)) (9.5.0)
> Requirement already satisfied: coverage in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 18)) (7.2.3)
> Requirement already satisfied: flake8 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from -r requirements.txt (line 19)) (6.0.0)
> Requirement already satisfied: aiohttp in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from openai==0.27.2->-r requirements.txt (line 3)) (3.8.4)
> Requirement already satisfied: tqdm in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from openai==0.27.2->-r requirements.txt (line 3)) (4.65.0)
> Requirement already satisfied: chardet in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 7)) (5.1.0)
> Requirement already satisfied: cssselect in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 7)) (1.2.0)
> Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from readability-lxml==0.8.1->-r requirements.txt (line 7)) (4.9.1)
> Requirement already satisfied: regex>=2022.1.18 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from tiktoken==0.3.3->-r requirements.txt (line 9)) (2023.3.23)
> Requirement already satisfied: click<8.2,>=7.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from gTTS==2.3.1->-r requirements.txt (line 10)) (8.1.3)
> Requirement already satisfied: loguru>=0.5.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (0.7.0)
> Requirement already satisfied: dnspython>=2.0.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (2.3.0)
> Requirement already satisfied: urllib3>=1.21.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (1.26.15)
> Requirement already satisfied: typing-extensions>=3.7.4 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (4.5.0)
> Requirement already satisfied: python-dateutil>=2.5.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (2.8.2)
> Requirement already satisfied: numpy in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pinecone-client==2.2.1->-r requirements.txt (line 14)) (1.24.2)
> Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from beautifulsoup4->-r requirements.txt (line 1)) (2.3.2.post1)
> Requirement already satisfied: certifi>=2017.4.17 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from requests->-r requirements.txt (line 8)) (2022.12.7)
> Requirement already satisfied: idna<4,>=2.5 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from requests->-r requirements.txt (line 8)) (3.4)
> Requirement already satisfied: charset-normalizer<4,>=2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from requests->-r requirements.txt (line 8)) (3.1.0)
> Requirement already satisfied: packaging>=14.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from docker->-r requirements.txt (line 11)) (21.3)
> Requirement already satisfied: websocket-client>=0.32.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from docker->-r requirements.txt (line 11)) (1.5.1)
> Requirement already satisfied: uritemplate<5,>=3.0.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 13)) (4.1.1)
> Requirement already satisfied: httplib2<1dev,>=0.15.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 13)) (0.22.0)
> Requirement already satisfied: google-auth<3.0.0dev,>=1.19.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 13)) (2.17.3)
> Requirement already satisfied: google-auth-httplib2>=0.1.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 13)) (0.1.0)
> Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-python-client->-r requirements.txt (line 13)) (2.11.0)
> Requirement already satisfied: async-timeout>=4.0.2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from redis->-r requirements.txt (line 15)) (4.0.2)
> Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from flake8->-r requirements.txt (line 19)) (2.10.0)
> Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from flake8->-r requirements.txt (line 19)) (0.7.0)
> Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from flake8->-r requirements.txt (line 19)) (3.0.1)
> Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client->-r requirements.txt (line 13)) (4.22.3)
> Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client->-r requirements.txt (line 13)) (1.59.0)
> Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (5.3.0)
> Requirement already satisfied: rsa<5,>=3.1.4 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (4.9)
> Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (0.2.8)
> Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (1.16.0)
> Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client->-r requirements.txt (line 13)) (3.0.9)
> Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 3)) (22.1.0)
> Requirement already satisfied: aiosignal>=1.1.2 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 3)) (1.3.1)
> Requirement already satisfied: frozenlist>=1.1.1 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 3)) (1.3.3)
> Requirement already satisfied: yarl<2.0,>=1.0 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 3)) (1.8.2)
> Requirement already satisfied: multidict<7.0,>=4.5 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from aiohttp->openai==0.27.2->-r requirements.txt (line 3)) (6.0.4)
> Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/emilyqiao/Library/Python/3.10/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (0.4.8)
> 
> emilyqiao@Emikos-Air Auto-GPT % python scripts/main.py
> Traceback (most recent call last):
>   File "/Users/emilyqiao/Desktop/Auto-GPT/scripts/main.py", line 3, in <module>
>     import commands as cmd
>   File "/Users/emilyqiao/Desktop/Auto-GPT/scripts/commands.py", line 1, in <module>
>     import browse
>   File "/Users/emilyqiao/Desktop/Auto-GPT/scripts/browse.py", line 1, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
