### ISSUE TITLE
ModuleNotFoundError : No Module Named "requests"

### ISSUE THREAD

**Issue by TunahanYelmer** [Torantulino/Auto-GPT#1133]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

İt throws an ModuleNotFound error right now. request.py module does not exists. I just cloned the Auto-GPT via console

### Expected behavior 🤔

İt should start chatting 

### Your prompt 📝

```yaml
# Paste your prompt here
```
python scripts/main.py

**Comment by jnt0rrente** [comment]
Did you follow the installation guide? Particularly the part where it says:

`pip install -r requirements.txt`

**Comment by GrzegorzKarczewski** [comment]
> Did you follow the installation guide? Particularly the part where it says:
> 
> `pip install -r requirements.txt`



> Yes i tried it it has given no errors executed succesfully, I suspect it probably because of python i'll try uninstall and reinstalling it.

Right now, something happened with file requirements.txt
You need to manually add requests and command to it or just do
pip install command
pip install requests

**Comment by TunahanYelmer** [comment]
i solved it , i manually installed command and  requests  but pip install command didnt work  i used  py -m pip install command
