### ISSUE TITLE
Auto-GPT does not run,says missing module

### ISSUE THREAD

**Issue by Dark-Ninja1** [Torantulino/Auto-GPT#1152]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I installed the packages, then ran main.py

### Current behavior 😯

It says there are missing packages.
![image](https://user-images.githubusercontent.com/68978192/231838405-35d513fc-c81d-4eb4-8585-8b2523d07c9a.png)
I have pip ver. 22.3.1

I have python ver. 3.10

### Expected behavior 🤔

It should run.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by p-i-** [comment]
Probably you didn't read the README.md and didn't `pip install -r requirements.txt`

https://github.com/Torantulino/Auto-GPT/blob/master/requirements.txt#L1

**Comment by Dark-Ninja1** [comment]
But, I did! I also installed beautifulsoup4 just in case.
