### ISSUE TITLE
python3 scripts/main.py.  command not working

### ISSUE THREAD

**Issue by FagerCrypto** [Torantulino/Auto-GPT#1210]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When I try to enter the code following error message appears: 
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: can't open file '/Users/felixbuhler/Auto-GPT/scripts/main.py.': [Errno 2] No such file or directory

I downloaded every file from the site. Thanks for helping me

**Comment by FagerCrypto** [comment]
Found the solution

**Comment by o-Tang** [comment]
what was it?

**Comment by Ericsongyl** [comment]
> 

What's the solution
