### ISSUE TITLE
AutoGPT cant find my API Keys

### ISSUE THREAD

**Issue by Rolduck** [Torantulino/Auto-GPT#1217]
I'm new to running things like this but i think the .env file is whats giving me issues, The file type will not change from TEMPLATE File to ENV. im running this on Windows 10, with Python 3.10.10, 

I gave the file my Open AI and Pinecone API keys, i renamed the file from ".env.template " to just ".env" but when i run "python scripts/main.py" i get "Please set your OpenAI API key in .env or as an environment variable. You can get your key from https://beta.openai.com/account/api-keys"

when i try opening the .ENV file in Notepad++ i can see the name still shows as ".env.template" but it does not show that in Notepad or Wordpad. Could this be the issue? I'm sure i entered the keys in the correct spots of the file itself

If Openj AI needs to verify my payment into first before the keys work that could also be the issue but then i dont know why it would still generate the keys.

if i need to run a command please specify where to run it otherwise i may try running it on a toaster <3

**Comment by tdaubs** [comment]
Do you have file name extensions turned on in Windows 10? If not, turn them on. That might help to see if your actually changing the file name extension correctly. You can also do this outside the terminal if that's easier.

**Comment by phouverneyuff** [comment]
I'm using linux and I need to:

```SHELL
mv .env env
mv env .env
```

**Comment by DrReefer** [comment]
![env](https://user-images.githubusercontent.com/20601270/231930745-60f24af3-4458-4f3b-9e9e-e7afc8c1835d.jpg)
I'm having the same problem. I even deleted and recloned it. This time I didn't have to rename it, just add my keys, did that but still getting Please set your OpenAI API key in .env or as an environment variable.

**Comment by richbeales** [comment]
Closing, OS issue with either hiding dotfiles, or hiding the file extension.  Use VSCode or Windows Terminal to view the folder

**Comment by kazegairoman** [comment]
I have already replace OPENAI_API_KEY in .env, but still return"Please set your OpenAI API key in .env or as an environment variable.",could anyone please help me with it, please?

**Comment by Rolduck** [comment]
regular file explore fail me i had to use my web browser to rename the .env file. thank you all for your help, i now get to name my pet.

**Comment by Okitrader** [comment]
Well, I think I fixed this problem by opening the project in vscode. Opening it via Finder on Mac did not help it would revert back to the .template name

**Comment by moein9gh** [comment]
put following code inside autogpt/__main__.py

import os
os.environ['OPENAI_API_KEY'] = '<YOUR_OPENAI_APIKEY>'


replace <YOUR_OPENAI_APIKEY> with your open api key

**Comment by korenhskoh** [comment]
Hi all,

For Window user it will fixed 100% 👍 

1. Go to file path until Auto-GPT-0.2.1
2. Then Click the .env
3. Click the top left of tab "View"
4. you will see the check box for the "File name extension" and "Hidden items"
5.  Make sure click **checked**  "File name extension" and **uncheck** "Hidden items"

![image](https://user-images.githubusercontent.com/56794226/232730124-5a985dc0-40a7-4a63-996a-2a6f171122eb.png)
