### ISSUE TITLE
error solved

### ISSUE THREAD

**Issue by autoswifty** [Torantulino/Auto-GPT#1218]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

ERROR:

C:\AI\autogpt\Auto-GPT>python scripts/main.py
Please set your OpenAI API key in .env or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

I have tried free and paid api keys, uninstalls and same result

Please help me troubleshoot and get AutoGPT functioning

### Current behavior 😯

error

### Expected behavior 🤔

run autogpt

### Your prompt 📝

C:\AI\autogpt\Auto-GPT>python scripts/main.py

**Comment by autoswifty** [comment]
sorry for duplicate, previous post solved problem for me

**Comment by richbeales** [comment]
closing

**Comment by AKACC** [comment]
@autoswifty Could you link your solution?
