### ISSUE TITLE
there is no .env.template file in  auto-gpt folder

### ISSUE THREAD

**Issue by jclp3827** [Torantulino/Auto-GPT#1261]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/12854194/231969413-acfc9bfd-5069-4af6-801f-a7cd1b46bf0e.png)
<img width="760" alt="image" src="https://user-images.githubusercontent.com/12854194/231969447-f6bbd3fa-d486-4bcb-9789-53625e2617f6.png">

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by karunakarhv** [comment]
Hidden files will be stored as "." extension. Please view it through terminal.

**Comment by zzzgydi** [comment]
try `Cmd + Shift + .`

**Comment by richbeales** [comment]
Setup issue - please look up how to view hidden files in your OS, or open in VSCode or similar.
