### ISSUE TITLE
Google Error 400 - Bad Request

### ISSUE THREAD

**Issue by sam1am** [Torantulino/Auto-GPT#127]
`SYSTEM:  Command google returned: Error: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=how+to+connect+to+wsl+on+network&cx=&num=8&key=MYSUPERSECRETKEY&alt=json returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]">
`

<img width="1025" alt="Screenshot 2023-04-03 at 8 50 05 PM" src="https://user-images.githubusercontent.com/127555/229658254-29615dbb-dc4f-425d-8f69-167500621d8e.png">

**Comment by sam1am** [comment]
That was it, thanks!

**Comment by Mister-Carter** [comment]
> > `SYSTEM: Command google returned: Error: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=how+to+connect+to+wsl+on+network&cx=&num=8&key=MYSUPERSECRETKEY&alt=json returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]"> `
> > <img alt="Screenshot 2023-04-03 at 8 50 05 PM" width="1025" src="https://user-images.githubusercontent.com/127555/229658254-29615dbb-dc4f-425d-8f69-167500621d8e.png">
> 
> I faced the same issue, and it occurred because I didn't follow all the steps mentioned here:
> 
> https://github.com/Torantulino/Auto-GPT#-google-api-keys-configuration
> 
> You need to follow this: "Go to the Custom Search Engine page and click "Add"" and copy the "**search engine id**" to CUSTOM_SEARCH_ENGINE_ID=**cx**... in the .env file.

I did this and it did not work. Does the search engine id need to be linked to the google api somehow? Any ideas of what I could be doing wrong? I put the google api key and the search engine id into the .env file then saved the file and opened a new command prompt window and it is still not working

**Comment by MukundaHolla** [comment]
I found the issue, it could be [here](https://github.com/Torantulino/Auto-GPT/blob/master/scripts/commands.py#L149) i was able to fix by initializing it directly here like this 
`custom_search_engine_id = 'SampleId12345'`

Since we are all trying to make this work in local for now, this fixes it for now. Might not be the perfect solution but works :)

**Comment by leozc** [comment]
You need to make sure to source `.env` file to ensure loading the environment variable in
