### ISSUE TITLE
What is the situation when the screen printing information goes up and down?

### ISSUE THREAD

**Issue by digger-yu** [Torantulino/Auto-GPT#128]
![2023-04-04-08-34-15](https://user-images.githubusercontent.com/55081697/229662077-80a884b2-8ade-4a16-babd-60c04d2222b7.gif)

**Comment by EricFedrowisch** [comment]
What shell?

**Comment by digger-yu** [comment]
> What shell?

See gif

**Comment by EricFedrowisch** [comment]
The gif isn't as informative as you may imagine. All it really shows is your command prompt. That tells me you are running as root on a *Nix base server. Likely then the shell is bash, but it could be many others (zsh, fish, sh, just off the top of my head). 

Try entering:
`echo $0`
or
`ps`
to have the shell tell you which it is.

The reason I ask, is that different shells handle whitespace, clearing the screen and other commands differently.

**Comment by digger-yu** [comment]
Thank you for your answer, the environment is just bash
```
root@server:~# echo $0
-bash
root@server:~#
```
When I run this command, the print message goes up
python3 main.py --gpt3only
I've tried running python3 main.py without arguments and printing the message up too

**Comment by jones386** [comment]
I get the same problem on debian 11 using zsh. The problem appears to be with spinner.Spinner(). If I edit scripts/main.py and I add a long delay to Spinner (line 296), the spinner only prints once then gets overwritten by the output. 

It's not a real solution but it's usable:
On line 296 of scripts/main.py change "Spinner("Thinking... "):" to "Spinner("Thinking... ", delay=20):"

**Comment by jones386** [comment]
> 

Wait, I found it. It's the backspace in scripts/spinner.py

Change line 20 

from: sys.stdout.write('\b' * (len(self.message) + 2))
to: sys.stdout.write('' * (len(self.message) + 2))

Removing the backspace "\b" totally resolves the issue.

**Comment by digger-yu** [comment]
> the issue.

It's great, it works.
