### ISSUE TITLE
The command "google" returns WinError 10060 from 4.14 noon.

### ISSUE THREAD

**Issue by ozil56** [Torantulino/Auto-GPT#1280]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I set the Google API key and custom search engine correctly
and OpenAI GPT API runs well
After several steps, the script attemps to use the "google" command, then error happens.
I'm using a VPN with US node and it worked well yesterday. So I think VPN is fine.

### Current behavior 😯

every attemps using Command="google" returns a WinError 10060.

### Expected behavior 🤔

It should work properly

**Comment by RaymRaym** [comment]
Try to ping google.com. I guess it will be a timeout

**Comment by handouy** [comment]
I have the same problem. Is there a solution?

**Comment by RaymRaym** [comment]
I think it's about the proxy.  -> This may help. https://stackoverflow.com/a/16312067/20066794

**Comment by TheSummerRain** [comment]
我也是同样的问题。如果不开代理就无法访问谷歌，开了代理又报这个错误，无言以对。

**Comment by handouy** [comment]
It is the inability to access Google that causes the robot to keep trying to access Google loop, wasting tokens

**Comment by ozil56** [comment]
I made 3 mistakes here, and here is the solution
1. switch the VPN to Tunnel mode, ping google.com to test it.
2. enable the custom search API, I forgot to do that.
then the scripts run well.

**Comment by handouy** [comment]
> 我在这里犯了 3 个错误，这是解决方案
> 
> 1. 将 VPN 切换到隧道模式，google.com ping 以对其进行测试。
> 2. 启用自定义搜索 API，我忘了这样做。然后脚本运行良好。

Do you know why I can access Google, but ping google.com shows a request timeout

**Comment by cshr25** [comment]
same issue here. I can open up Google in Chrome but can't ping it through.

**Comment by chunyanghu** [comment]
I have the same problem

**Comment by usamimeri** [comment]
I also encounter this problem while using a proxy

**Comment by zihengyu** [comment]
same problem for me with proxy

**Comment by TylerDurdenT** [comment]
> I made 3 mistakes here, and here is the solution我在这里犯了 3 个错误，这是解决方案
> 
> 1. switch the VPN to Tunnel mode, ping google.com to test it.将 VPN 切换到隧道模式，ping google.com 进行测试。
> 2. enable the custom search API, I forgot to do that.启用自定义搜索 API，我忘了这样做。
>    then the scripts run well. 然后脚本运行良好。

Correct.

Just Switch VPN to tun mode, problem solved！

**Comment by watchthesunset** [comment]
It could be a problem with the network proxy. I had the same problem. This problem can occur if Auto-GPT uses google scholar.

**Comment by joisonwk** [comment]
我是Windows环境，上面提供的方法对我好像没用，我在scripts的main.py 头部加上这几行代码不再10060错误
