### ISSUE TITLE
gpt-3.5 returns gibberish

### ISSUE THREAD

**Issue by Wladastic** [Torantulino/Auto-GPT#1298]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Temperature=1

I have had it at 2 before, but it became horrible.
Is something wrong with openai or is that due to some prompt being faulty?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by MingStar** [comment]
try set the Temperature to a much lower value, like 0.1

**Comment by Wladastic** [comment]
you saved my life :D
