### ISSUE TITLE
建了个群来一起研究部署这个，好玩儿，VX: connection-image 我拉你

### ISSUE THREAD

**Issue by yyx20202020** [Torantulino/Auto-GPT#1374]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

一个人搞，好多细节不太懂，大家一起交流切磋，拉几个大牛进来

VX: connection-image  备注：Auto-GPT ；拉你进群

**Comment by richbeales** [comment]
closing as we can't currently support issues raised in languages other than english
