### ISSUE TITLE
.env.template file not downloading

### ISSUE THREAD

**Issue by g0lakers** [Torantulino/Auto-GPT#1387]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

downloading the .zip file or doing a file import does not show the .env.template file

### Current behavior 😯

cannot see the file

### Expected behavior 🤔

the file should be there and i should be able to edit the contents

**Comment by mattpotma** [comment]
What platform are you on? Any file starting with a `.` is a "hidden" file. I don't know how to show them on Windows, but ChatGPT can probably tell you how to show hidden files for whatever platform you are on.

**Comment by richbeales** [comment]
dotfile almost certainly hidden on your OS. closing.
