### ISSUE TITLE
Docker build can't load module: "/usr/local/bin/python: No module named autogpt"

### ISSUE THREAD

**Issue by overkill32** [Torantulino/Auto-GPT#1406]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

`git clone https://github.com/Torantulino/Auto-GPT.git`

`cd Auto-GPT/`

`docker build -t autogpt .`

`docker run -it --env-file=../../.env -v $PWD/auto_gpt_workspace:/app/auto_gpt_workspace autogpt`

### Current behavior 😯

The docker container exits with the error: 

`/usr/local/bin/python: No module named autogpt`

### Expected behavior 🤔

Docker container starts

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by darkcount2011** [comment]
I think somewhere in the build it doesn't correctly load everything from requirements.txt, and since local is also not working because of missing imports and requirements.txt, I assume that is the problem

**Comment by LegoFighter** [comment]
pip3 install --upgrade pip

**Comment by overkill32** [comment]
Thanks @LegoFighter , but I did try that.   @darkcount2011 got me thinking and looking into the Dockerfile. The root cause was the Dockerfile COPY command is blowing away the autogpt parent directory when the build runs.

I fixed that and also added a copy missing items to the requirements.txt file with [this PR](https://github.com/Torantulino/Auto-GPT/pull/1425).

**Comment by richbeales** [comment]
closing as superseded by v0.2.0

**Comment by GHowlett** [comment]
> closing as superseded by v0.2.0

I'm still getting this issue

**Comment by ziipzaaapM16A4** [comment]
> I'm still getting this issue

me too

**Comment by TodorDimitrovIvanov** [comment]
Same issue here after a fresh install and when using the stable branch

**Comment by KenWuqianghao** [comment]
same issue here

**Comment by armbjs** [comment]
I have same problem.

**Comment by daniel-alejandro-t** [comment]
If you use podman use:
`podman build --format=docker -t auto-gpt .
`
