### ISSUE TITLE
In --gpt3only mode, receive this error: SYSTEM:  Command evaluate_code returned: Error: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by jtokash** [Torantulino/Auto-GPT#145]
When running with --gpt3only mode, I receive this error when Auto-GPT tries to 'execute' code.

SYSTEM:  Command evaluate_code returned: Error: The model: `gpt-4` does not exist

**Comment by Tonylib** [comment]
same

**Comment by ljleb** [comment]
Same problem. Can anyone call the openapi for gpt-4 or you need to be granted access?

**Comment by stayupthetree** [comment]
> Same problem. Can anyone call the openapi for gpt-4 or you need to be granted access?

From what I can tell you need to sign up on a waitlist for gpt-4 API

**Comment by griffintv** [comment]
Can you disable and only have it run on 3.5?

**Comment by jcdescy** [comment]
I get the same, but I'm not running in gpt3only mode. It was when the AI had written a bot and tried to evaluate the code.

**Comment by ljleb** [comment]
To disable gpt-4 just edit the configuration, set `SMART_LLM_MODEL="gpt-3.5-turbo"` in `.env`.

**Comment by jtokash** [comment]
@ljleb 's response is correct - there are 2 models referenced in .env.  I only had one set to 3.5.

**Comment by Wladastic** [comment]
PINECONE_API_KEY=your-pinecone-api-key
PINECONE_ENV=your-pinecone-region
OPENAI_API_KEY=
ELEVENLABS_API_KEY=
SMART_LLM_MODEL="gpt-3.5-turbo-0301"
FAST_LLM_MODEL="gpt-3.5-turbo"
GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=
USE_AZURE=False
OPENAI_API_BASE=your-base-url-for-azure
OPENAI_API_VERSION=api-version-for-azure
OPENAI_DEPLOYMENT_ID=deployment-id-for-azure
IMAGE_PROVIDER=dalle
HUGGINGFACE_API_TOKEN=

**Comment by omni-webdev** [comment]
--gpt3only also resolves, don't have to set the env variable


> To disable gpt-4 just edit the configuration, set `SMART_LLM_MODEL="gpt-3.5-turbo"` in `.env`.

--gpt3only also resolves, don't have to set the env variable

**Comment by ljleb** [comment]
> @omni-webdev --gpt3only also resolves, don't have to set the env variable

Unless it has been fixed, (I assume it has been fixed by now?) there was an issue last week making this flag useless for code.

**Comment by styk-tv** [comment]
@ljleb looks like it was fixed, no more gpt4 errors with the flag

**Comment by Deano007** [comment]
Command evaluate_code returned: Error: The model: `gpt-4` does not exist

I have openAPI key and following in .env file, what am I missing?

SMART_LLM_MODEL=gpt-4
FAST_LLM_MODEL=gpt-3.5-turbo

**Comment by dawidkulpa** [comment]
Having paid OpenAI account doesn't neccessarily mean you have access to GPT4 (neither does ChatGPT Plus subscription), currently the only way to get access to GPT4 is through waitlist: https://openai.com/waitlist/gpt-4-api

**Comment by LuigiCosi** [comment]
@styk-tv I still get this error and all I get is: SYSTEM:  

Command evaluate_code returned: Error: The model: `gpt-4` does not exist 
although in .env I have: 

"SMART_LLM_MODEL="gpt-3.5-turbo"
FAST_LLM_MODEL=gpt-3.5-turbo"

**Comment by GlobalSCEO** [comment]
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command evaluate_code returned: Error: The model: `gpt-4` does not exist
I didn't know so i waste 0.17 token. why is it spending money and my time?....

**Comment by Deano007** [comment]
> Having paid OpenAI account doesn't neccessarily mean you have access to GPT4 (neither does ChatGPT Plus subscription), currently the only way to get access to GPT4 is through waitlist: https://openai.com/waitlist/gpt-4-api

It's still able to use gtp-3.5-turbo and that's where your tokens are being spent, access to the API is not free

**Comment by Abdulsamipy** [comment]
> -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= SYSTEM: Command evaluate_code returned: Error: The model: `gpt-4` does not exist I didn't know so i waste 0.17 token. why is it spending money and my time?....

Please are working hard on the project. if u think it wasting your time , DON'T USE IT
