### ISSUE TITLE
running data ingestion without init wipes auto_gpt.json

### ISSUE THREAD

**Issue by Jonathantsho** [Torantulino/Auto-GPT#1451]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python3 scripts/data_ingestion.py --file  <your file/dir here>

### Current behavior 😯

watch auto_gpt.json get wiped out when starting autogpt, or when data_ingestion.py is run

### Expected behavior 🤔

It should append, rather than wipe the file. Vice versa, when gpt is run (no matter what step), it wipes the data_ingestion data

**Comment by Qoyyuum** [comment]
Hi @Jonathantsho what did you set up for `WIPE_REDIS_ON_START` in your `.env` file?

**Comment by Jonathantsho** [comment]
Turns out this only supports redis. Closing!
