### ISSUE TITLE
目前正在看工作机会，坐标武汉，岗位前端开发，如果有合适的岗位推荐欢迎私信我 🙏

### ISSUE THREAD

**Issue by wjp2018** [Torantulino/Auto-GPT#1479]
1：精通DIV+CSS，熟练设计页面架构和布局。
2：熟练掌握Bootstrap、EasyUI和WeUi框架，能够快速应用于项目开发。
3：熟练掌握响应式布局和移动端开发，注重优秀的用户体验和交互设计。
4：熟悉HTML5和CSS3的新特性，深入了解用户需求和操作流程。
5：熟练掌握JavaScript和ES6，善于Web页面开发。
6：熟练使用Photoshop进行UI设计、切图和图标处理。
7：熟悉简单Oracle数据库和SQL语句。
8：熟练使用WinSCP和Xshell 5，可简单操作tomcat、linux和nginx服务器的部署环境。
9：熟悉软件开发和测试流程，能够编写优质文档。
10：熟练制作微信小程序前端页面和接口调用，以及HTML5手机移动端页面。
11：熟练掌握Vue框架和Element、Vant、uiapp组件库开发。
12：熟练使用svn和git工具，熟悉HBuilder、eclipse、IntelliJ IDEA和VSCode等开发工具。

**Comment by richbeales** [comment]
english only please

**Comment by wjp2018** [comment]
Currently looking at job opportunities, coordinates in Wuhan, China, post Web front-end development, if you have a suitable job recommendation, please feel free to private message me
