### ISSUE TITLE
cannot import name '_tiktoken' from partially initialized module 'tiktoken'

### ISSUE THREAD

**Issue by ssSStking** [Torantulino/Auto-GPT#157]
from tiktoken import _tiktoken
ImportError: cannot import name '_tiktoken' from partially initialized module 'tiktoken' (most likely due to a circular import) (D:\anaconda3\envs\pythonProject\lib\site-packages\tiktoken\__init__.py)

my tiktoken==0.3.3

**Comment by amauryfischer** [comment]
what are your other versions from requirements.txt ?
there is an issue with circular dependencies with googlesearch

**Comment by amauryfischer** [comment]
checkout https://github.com/Torantulino/Auto-GPT/pull/98

**Comment by Aashishkumar123** [comment]
Upgrade your tiktoken version

`pip3 install tiktoken --upgrade`
