### ISSUE TITLE
bug when running AUTO-GPT

### ISSUE THREAD

**Issue by marcus35000** [Torantulino/Auto-GPT#173]
Hi Torantulino
What a great work !
I have this error message when I run Auto-GPT, any ideas ?
Continue (y/n): y
Warning: model not found. Using cl100k_base encoding.
Traceback (most recent call last):
  File "/Users/marc/Auto-GPT/scripts/main.py", line 287, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/Users/marc/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    current_tokens_used = token_counter.count_message_tokens(current_context, model)
  File "/Users/marc/Auto-GPT/scripts/token_counter.py", line 33, in count_message_tokens
    raise NotImplementedError(f"""num_tokens_from_messages() is not implemented for model {model}. See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.""")
NotImplementedError: num_tokens_from_messages() is not implemented for model . See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.

**Comment by Big-jpg** [comment]
It's all right there in your error code.

First look at line 287 in main.py, which leads you to look at line 67 in chat.py, which also leads to line 33 in the token_counter.py file

I would suggest wrapping those three areas in a try catch block and then outputting the error to the console.

Also check your .env file in the root of your directory has a defined API key for OpenAI and models set as the fast and smart llm vars.

**Comment by marcus35000** [comment]
Thanks Big-Jpg, the problem came from my .env under Mac. It had still initial extension .template so I renamed it and it's alright !
