### ISSUE TITLE
No module named 'openai'

### ISSUE THREAD

**Issue by kotaxyz** [Torantulino/Auto-GPT#196]
hello there i get this error , even i did pip install openai,im on free plan for chatgpt ,so do i need paid plan to make it work

X:\Auto-GPT>python scripts/main.py --speak
Traceback (most recent call last):
  File "X:\Auto-GPT\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "X:\Auto-GPT\scripts\commands.py", line 1, in <module>
    import browse
  File "X:\Auto-GPT\scripts\browse.py", line 3, in <module>
    from config import Config
  File "X:\Auto-GPT\scripts\config.py", line 2, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by kotaxyz** [comment]
fixed just install with conda

**Comment by EricFedrowisch** [comment]
Sorry you are having trouble. What operating system are you using? Sometimes there can be more than one version of python installed and this can cause issues where pip installs the package in one but not the one you mean to use.

Perhaps try:
`python -m pip install openai`

**Comment by kotaxyz** [comment]
thanks for your reply i was able to fix it by creating virtual environment with anaconda through python 3.10 , everything is working now
