### ISSUE TITLE
Millisecond time included to the left of output, making it hard to read.

### ISSUE THREAD

**Issue by kingcharlezz** [Torantulino/Auto-GPT#200]
←[32m-  ←[0mConduct a specific and detailed Google search to emphasize Python integration of Twilio's appointment scheduling API.
←[32m-  ←[0mReview the documentation to find optimal use of the API in the upcoming project.
←[33mCRITICISM: ←[0mChoosing the right search keywords will help us to find the most relevant and widely used documentation, which will provide best practice insights and tips for integrating the API into our system at a low cost. It's critical to prioritize thoroughness and attention to detail to ensure an effective Python-Twilio API integration.
←[36mNEXT ACTION:  

here is an example. Is there a command to fix this?

**Comment by RossHaroldson** [comment]
I would also like to figure out how to get rid of this

**Comment by Monkee1337** [comment]
#117

**Comment by drnoi** [comment]
> ←[32m- ←[0mConduct a specific and detailed Google search to emphasize Python integration of Twilio's appointment scheduling API. ←[32m- ←[0mReview the documentation to find optimal use of the API in the upcoming project. ←[33mCRITICISM: ←[0mChoosing the right search keywords will help us to find the most relevant and widely used documentation, which will provide best practice insights and tips for integrating the API into our system at a low cost. It's critical to prioritize thoroughness and attention to detail to ensure an effective Python-Twilio API integration. ←[36mNEXT ACTION:
> 
> here is an example. Is there a command to fix this?

That number you're seeing is ANSI code number for display colored text. Run the Python code in VSCode and you'll see different text colors. Regular consoles don't interpret the numbers.
