### ISSUE TITLE
"Incorrect API key provided" error - I think the repo has a hardcoded OpenAI Key?

### ISSUE THREAD

**Issue by voidxd** [Torantulino/Auto-GPT#204]
Hello.

I'm unable to use Auto-GPT since even though I provide my OpenAI key, every time I get this exact error

```
openai.error.AuthenticationError: Incorrect API key provided: sk-8uKxH***************************************MvFD. You can find your API key at https://platform.openai.com/account/api-keys.
```

Every time the key is `sk-8uKxH***************************************MvFD` even though I've changed it, deleted the repo and ran it again.

And I can't find where this `sk-8uKxH***************************************MvFD` key is hardcoded.

Am I missing something?

Thank you!

**Comment by stayupthetree** [comment]
Just to verify, you dont have that exact API key posted in right? with all the **********************?
Also very you're API key in the .env file you created

**Comment by slavakurilyak** [comment]
@voidxd as per [installation](https://github.com/Torantulino/Auto-GPT#-installation) instructions, create `.env` from [.env.template](https://github.com/Torantulino/Auto-GPT/blob/master/.env.template), then update your `OPENAI_API_KEY`

**Comment by stayupthetree** [comment]
> @stayupthetree @slavakurilyak
> 
> 1. I renamed my `.env.template` file into `.env`
> 2. I filled in my OpenAI API key in the format `OPENAI_API_KEY="sk-abcde***************************************wxyz"`
>    ![image](https://user-images.githubusercontent.com/58847957/229913578-43aeeec1-d74c-4d2b-98e8-36ff64b083f1.png)
> 3. Even though that is the API key I filled in, I still get the exact same error output with the key ending in `MvFD`
>    ![image](https://user-images.githubusercontent.com/58847957/229913744-ba65b511-f57d-4b8f-b725-a0e1873b8e78.png)

There shouldn't be any ******************************* also unclear if the " " will mess anything up, but those also aren't in the template

**Comment by stayupthetree** [comment]
OpenAI, obfuscates your API after you generate it. This means you have one chance to copy it, otherwise you need to generate a new one and copy it before it gets obfuscated in the UI.

**Comment by Megachill** [comment]
Same here, confirmed. New install as well, new key generated. Key shown in error does not match the one in .env

**Comment by voidxd** [comment]
@Megachill Is the key shown the exact same one that I'm shown?

**Comment by Megachill** [comment]
@voidxd This is my error key: 

`Incorrect API key provided: sk-1h0AW***************************************2hBN. `

**Comment by Megachill** [comment]
@voidxd  In TTL same for me:

`Incorrect API key provided: sk-1h0AW***************************************2hBN.`

**Comment by voidxd** [comment]
@Megachill I think it's due to having an old environment variable setup on your system as `OPENAI_API_KEY`. I found mine and removed it and it works.

**Comment by Megachill** [comment]
@voidxd you sir are a life saver - i had the same issue

**Comment by beast1xy** [comment]
for me, the solution was to name the .env.template file to just .env

and i wrote the thing with the api key like that:
OPENAI_API_KEY=sk-1ykb......EKTL

so, i don't your quotation marks like: "
now it works for me
