### ISSUE TITLE
Build in Rate-Limit Error Handling

### ISSUE THREAD

**Issue by nathanlannan** [Torantulino/Auto-GPT#22]
Below is a readout from an example error.

"I hit a rate limit error working with the OpenAI API: File "D:\projects\auto-gpt\auto-gpt-env\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.RateLimitError: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists."

Traceback (most recent call last):
  File "D:\projects\auto-gpt\auto-gpt\scripts\main.py", line 199, in <module>
    assistant_reply = chat.chat_with_ai(
  File "D:\projects\auto-gpt\auto-gpt\scripts\chat.py", line 80, in chat_with_ai
    except openai.RateLimitError:
AttributeError: module 'openai' has no attribute 'RateLimitError'

Would it be possible to throttle the script depending on the model being executed?
https://platform.openai.com/docs/guides/rate-limits/overview

**Comment by Torantulino** [comment]
Thanks for submitting this Nathan,

It is indeed possible and a good idea, adding it to the to-do list!

**Comment by nathanlannan** [comment]
I think I found the fix:

in chat.py

try:
    # your code that sends requests to OpenAI
    return assistant_reply
except openai.error.RateLimitError:
    print("Error: ", "API Rate Limit Reached. Waiting 60 seconds...")
    time.sleep(60)

Basically just switching form openai.RateLimitError to openai.error.RateLimitError

**Comment by Torantulino** [comment]
Thank you very much :)
