### ISSUE TITLE
How do I complete number 4? 

### ISSUE THREAD

**Issue by brunsonator3** [Torantulino/Auto-GPT#230]
I'm in command prompt. I installed pip requirements. Now what?

Rename .env.template to .env and fill in your OPENAI_API_KEY. If you plan to use Speech Mode, fill in your ELEVEN_LABS_API_KEY as well.

How do I rename in command prompt after I install the requirements?
![number 4 Screenshot 2023-04-04 231605](https://user-images.githubusercontent.com/115924424/229979733-e9b5d7cd-1549-4084-9ded-6fe1beb00ea3.png)

**Comment by Provello** [comment]
could do `cp .env.template .env`

This will copy and rename the `.env.template` to just `.env`

Then you can edit this file with the required keys

**Comment by brunsonator3** [comment]
> could do `cp .env.template .env`
> 
> This will copy and rename the `.env.template` to just `.env`
> 
> Then you can edit this file with the required keys
> 
> Tip: this is just a folder on your computer, so you can do it as you would normally in a file browser, just open your files `WIN + E` and navigate to `C:\ -> Users -> YOURUSER -> Auto-GPT` and there you will see all of the files you have downloaded. You can right click copy and paste then right-click edit the file and open with notepad or your favourite text editor like Sublime or VSCode

Thanks!

**Comment by brunsonator3** [comment]
> cp .env.template .env

Wait don't you mean?: cd .env.template .env

**Comment by brunsonator3** [comment]
It says "'cp' is not recognized as an internal or external command,
operable program or batch file."

**Comment by ArchEight** [comment]
> I'm in command prompt. I installed pip requirements. Now what?
> 
> Rename .env.template to .env and fill in your OPENAI_API_KEY. If you plan to use Speech Mode, fill in your ELEVEN_LABS_API_KEY as well.
> 
> How do I rename in command prompt after I install the requirements? ![number 4 Screenshot 2023-04-04 231605](https://user-images.githubusercontent.com/115924424/229979733-e9b5d7cd-1549-4084-9ded-6fe1beb00ea3.png)

To rename the `.env.template` file to `.env` in the command prompt, you can use the `ren` command. First, navigate to the folder containing the `.env.template` file using the `cd` command. Assuming the file is in the `Auto-GPT` folder, you can do this by running:

```bash
cd C:\Users\Auto-GPT
```

After navigating to the correct folder, run the following command:

```bash
ren .env.template .env
```

This will rename the `.env.template` file to `.env`. Now, you can open the `.env` file with a text editor of your choice (e.g., Notepad) and fill in your `OPENAI_API_KEY` and `ELEVEN_LABS_API_KEY` if needed.

Remember to save the file after updating the keys.

**Comment by brunsonator3** [comment]
Hey so I figured it out instead of typing the cp in: cp .env.template .env
I instead put copy: copy .env.template .env
Apparently my windows CMD didn't recognize 'cp' and so I had to type in 'copy' instead.

Thank you all.

**Comment by BhavyeKhetan** [comment]
I can't find the file in Auto GPT
