### ISSUE TITLE
Another Requirements issue.

### ISSUE THREAD

**Issue by Jitone1** [Torantulino/Auto-GPT#231]
E:\Program FilesStable Diffusion\autogpt\Auto-GPT>pip install -r requirements.txt
Fatal error in launcher: Unable to create process using '"c:\users\office\appdata\local\programs\python\python39\python.
exe"  "C:\Users\Office\AppData\Local\Programs\Python\Python39\Scripts\pip.exe" install -r requirements.txt': The system
cannot find the file specified.
----------------------------------------------------
i removed the version numbers too from the requirements
beautifulsoup4
colorama
openai
playsound
python-dotenv
pyyaml
readability-lxml
requests
tiktoken
gTTS
docker
duckduckgo-search
google-api-python-client #(https://developers.google.com/custom-search/v1/overview) 

???

**Comment by theseraphim** [comment]
user error

**Comment by Mars-e** [comment]
Please try this list instead:

beautifulsoup4
colorama==0.4.6
openai==0.27.2
playsound==1.3.0
python-dotenv==1.0.0
pyyaml==6.0
readability-lxml==0.8.1
requests
tiktoken==0.3.3
gTTS==2.3.1
docker
duckduckgo-search
google-api-python-client #(https://developers.google.com/custom-search/v1/overview)

**Comment by Jitone1** [comment]
python -m pip install -r requirements.txt  worked.
