### ISSUE TITLE
Providing manual input in continuous mode

### ISSUE THREAD

**Issue by Provello** [Torantulino/Auto-GPT#236]
It would be helpful to have a feature where you can intervene and steer the continuous mode if it gets off track while watching it in action. One suggestion could be to implement a key that allows the model to finish its current task and then prompts the user for intervention to steer it back on track.

Another idea could be to add a variable that determines how many steps the model should run before pausing and asking for input. For example, the model could be set to run for 15 steps before checking in with the user to ensure it's still on the right track. This could create a more hands-off manual mode that still allows for user intervention when needed.

**Comment by slavakurilyak** [comment]
Interesting ideas, to say the least. Here's a similar one: https://github.com/Torantulino/Auto-GPT/issues/150

**Comment by fire17** [comment]
> It would be helpful to have a feature where you can intervene and steer the continuous mode if it gets off track while watching it in action. One suggestion could be to implement a key that allows the model to finish its current task and then prompts the user for intervention to steer it back on track.

Check out  https://github.com/Torantulino/Auto-GPT/pull/146 send to be with in progress

> Another idea could be to add a variable that determines how many steps the model should run before pausing and asking for input.

In general it should be straight forward to pause at any step, edit course, and resume , including config for time delays, and run

**Comment by hamidrezaabroshan** [comment]
very good comment

**Comment by Provello** [comment]
Ah, ok! It appears that my search has failed me! Was probably searching for too generic a term or something! Looking forward to seeing the development continue.

**Comment by Provello** [comment]
Appears to be implemented.
