### ISSUE TITLE
Command google returned: Error: 429 Client Error: Too Many Requests

### ISSUE THREAD

**Issue by jcdescy** [Torantulino/Auto-GPT#246]
Whenever the AI tries to use google, this error message comes up on the first try. 

`Command google returned: Error: 429 Client Error: Too Many Requests`

**Comment by stayupthetree** [comment]
Per the instructions if you encounter that error you need to do this https://github.com/Torantulino/Auto-GPT#-google-api-keys-configuration

**Comment by jcdescy** [comment]
Thanks! Seems I've overlooked that. Sorry. Now I get "Command Google Search returned: Unknown command Google Search", but that might be another issue.

**Comment by jcdescy** [comment]
Pulled new version and reinstalled. Google seems to work now. Thanks!
