### ISSUE TITLE
Access is denied: 'auto_gpt_workspace'

### ISSUE THREAD

**Issue by derekAglaeser** [Torantulino/Auto-GPT#303]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

In CMD when running python scripts/main.py I get the error Access is denied: 'auto_gpt_workspace' here is the CMD output

D:\AutoGPT\Auto-GPT-master>python scripts/main.py
Traceback (most recent call last):
  File "D:\AutoGPT\Auto-GPT-master\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "D:\AutoGPT\Auto-GPT-master\scripts\commands.py", line 9, in <module>
    from file_operations import read_file, write_to_file, append_to_file, delete_file, search_files
  File "D:\AutoGPT\Auto-GPT-master\scripts\file_operations.py", line 8, in <module>
    os.makedirs(working_directory)
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'auto_gpt_workspace'

Any help would be appreciated.

### Current behavior 😯

Permissions Error

### Expected behavior 🤔

Access

### Your prompt 📝

no prompt

**Comment by kevzy** [comment]
try running it as administrator

**Comment by kevzy** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Steps to reproduce 🕹
> In CMD when running python scripts/main.py I get the error Access is denied: 'auto_gpt_workspace' here is the CMD output
> 
> D:\AutoGPT\Auto-GPT-master>python scripts/main.py Traceback (most recent call last): File "D:\AutoGPT\Auto-GPT-master\scripts\main.py", line 3, in import commands as cmd File "D:\AutoGPT\Auto-GPT-master\scripts\commands.py", line 9, in from file_operations import read_file, write_to_file, append_to_file, delete_file, search_files File "D:\AutoGPT\Auto-GPT-master\scripts\file_operations.py", line 8, in os.makedirs(working_directory) File "", line 225, in makedirs PermissionError: [WinError 5] Access is denied: 'auto_gpt_workspace'
> 
> Any help would be appreciated.
> 
> ### Current behavior 😯
> Permissions Error
> 
> ### Expected behavior 🤔
> Access
> 
> ### Your prompt 📝
> no prompt

try running it as administrator

**Comment by derekAglaeser** [comment]
Thank you so much this help resolve the issue and it is working fine.
