### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed 

### ISSUE THREAD

**Issue by Nishant1997** [Torantulino/Auto-GPT#307]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. setup as per the documentation
2. run AutoGPT using ''python main.py --gpt3only "
3. after adding first few answers upto "Enter AI's Goal", I am getting below error.

 

### Current behavior 😯

It is throwing below " socket connection" error.
Traceback (most recent call last):
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection    
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Binjal Kadivar\anaconda3\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request        
    self._validate_conn(conn)
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn       
    conn.connect()
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\Binjal Kadivar\anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001EB431E8E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

### Expected behavior 🤔

Add goals in the database and moves on with other questions.

### Your prompt 📝

I am using VS code.

**Comment by PsiClone99** [comment]
Same error!

**Comment by hafometh88** [comment]
I am experiencing the same behavior.

**Comment by HappyCatKitten** [comment]
Same error

**Comment by HappyCatKitten** [comment]
I added the pinecone api key and region and it appears to work now

**Comment by hafometh88** [comment]
> I added the pinecone api key and region and it appears to work now

This worked, thanks.  It seems that using pinecone is required.

**Comment by Nishant1997** [comment]
I have added pinecode api key and region. but, I am getting "Error:  API Rate Limit Reached. Waiting 10 seconds..." error

**Comment by AlexBerejnov** [comment]
What do you put in the Pinecode region?

**Comment by Nishant1997** [comment]
![image](https://user-images.githubusercontent.com/20357250/230370685-3c55f773-5453-4624-89fa-415241767fe5.png)
PINECONE_ENV=us-east4-gcp

**Comment by PsiClone99** [comment]
Problem resolved after adding both the api key and the environment!

Thank you peeps!!

**Comment by Nishant1997** [comment]
Enter nothing to load defaults, enter nothing when finished.
Goal 1: best
Goal 2: best
Goal 3: best
Goal 4: best
Goal 5: best
Using memory of type: PineconeMemory
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

**Comment by Nishant1997** [comment]
@PsiClone99  can you please share your configuration file? I want to compare what am I missing here.

**Comment by Nishant1997** [comment]
I am getting below error. 
Using memory of type: PineconeMemory
Error: API Rate Limit Reached. Waiting 10 seconds...
Error: API Rate Limit Reached. Waiting 10 seconds...

REASON : 
- My Open AI API Key has expired. So, I am unable to receive the response from open ai.

SOLUTION : 
- Get a new API key

**Comment by TheZaind** [comment]
Same problem! Tried everything but the problem is still there.

**Comment by Poonam271998** [comment]
An error occurred: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'host' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)


how to fix this error. pls help
