### ISSUE TITLE
Solve the API cost issue! Free unlimited GPT-3.5 & GPT-4

### ISSUE THREAD

**Issue by tonymacx86PRO** [Torantulino/Auto-GPT#310]
### Duplicates

- [X] I have searched the existing issues

### I am done some research about how I can use GPT-4 API for free with unlimited query!
**Please don't abuse it**
How you can do it?
Register on [MindsDB (It's a SQL database that integrates AI into it)](https://mindsdb.com/)
Now you maked a demo account that can create 2 models in the demo instance with openai (NO API KEY NEEDED), hf, tensorflow or pytorch
Now you can "train" models with ur parameters like temperature, top_p and system prompt (prompt template)

Here's some sql queries to do some stuff

```sql
-- "Train" a model (For example gpt4)
CREATE MODEL mindsdb.gpt4 -- mindsdb.[yourmodelname]
PREDICT response -- What we want from model  a response!
USING -- Using WHAT?
engine = 'openai', -- OpenAI Engine
max_tokens = 6000, -- Adjusted max token size to 6k, you can make also temperature and more stuff...
-- api_key = demo instances already have one
model_name = 'gpt-4', -- you can also use text-davinci-003 or gpt-3.5-turbo
prompt_template = 'You are ChatGPT a large language model trained by OpenAI. Answer as concisely as possible. Knowledge cutoff: 2021 (year)\
Question: {{text}} Answer:'; -- Prompt template is similar to System Prompt
```

```sql
-- View the status of model
SELECT * -- Select all
FROM mindsdb.models -- From models table
WHERE name='gpt4'; -- Where is [yourmodelname] model
```
```sql
-- Query the model to response
SELECT response from mindsdb.[yourmodelname] WHERE text="[Prompt]";
```

```sql
-- Delete model
DROP MODEL mindsdb.gpt4; -- mindsdb.[yourmodelname]
```

And the awesome part u can use it with python using sql connector and ur credentials :D
```python
import mysql.connector
import os

mindsdb = mysql.connector.connect(
    host = "cloud.mindsdb.com",
    user = os.environ.get("USER"),
    password = os.environ.get("PASSWORD"),
    port="3306"
)
cursor = mindsdb.cursor()

cursor.execute('''
SELECT response from mindsdb.gpt4
WHERE 
text="Make a mini rap about factory";
'')
for x in cursor:
     print(cursor)
```

More in [MindsDB Docs](https://docs.mindsdb.com/what-is-mindsdb)

### Motivation 🔦

This will affect all comunity that uses paid expensive GPT-4 to make auto-tasks!

**Comment by amauryfischer** [comment]
I'm not sur this is under MindsDB terms of use. As they are paying to use openai on their side.

**Comment by tonymacx86PRO** [comment]
And i am not sure

**Comment by tonymacx86PRO** [comment]
In general, the worst part is that there are no analogues of GPT-4 and therefore you can't stupidly use this project

**Comment by tonymacx86PRO** [comment]
I don't understand at all why OpenAI closed its GPT-4 in paper?

**Comment by tonymacx86PRO** [comment]
Just then this project is useless if you can't pay for the API, I don't want to pay OpenAI at all just because there's no Paypal there and there's a credit card to leak it

**Comment by tonymacx86PRO** [comment]
> I'm not sur this is under MindsDB terms of use. As they are paying to use openai on their side.

What do you suggest?

**Comment by amauryfischer** [comment]
@tonymacx86PRO I suggest you put 5 dollard on a virtual card so you can avoid card leak

**Comment by tonymacx86PRO** [comment]
> @tonymacx86PRO I suggest you put 5 dollard on a virtual card so you can avoid card leak

I can't!

**Comment by crypticsymmetry** [comment]
super interesting, did you find a way to use it with auto gpt?

**Comment by tonymacx86PRO** [comment]
If u can connect via SQL connector and use it, u can of course!

**Comment by crypticsymmetry** [comment]
can you show me how you implemented it into the Auto-Gpt code? im curious how gpt4 works with it.

**Comment by tonymacx86PRO** [comment]
Like I have idea to make integration of sql mindsdb base but i have not
implemented it yet

вс, 9 апр. 2023 г. в 23:55, crypticsymmetry ***@***.***>:

**Comment by tonymacx86PRO** [comment]
Maybe i will download AutoGPT and patch it

пн, 10 апр. 2023 г. в 00:00, LinuxTechRUSGaming ***@***.***>:

**Comment by tonymacx86PRO** [comment]
But my problem that mysql connector can't connect to the server with my auth
I am still using via web editor

пн, 10 апр. 2023 г. в 00:01, LinuxTechRUSGaming ***@***.***>:

**Comment by crypticsymmetry** [comment]
apparently you can only use it within there web editor, to use it locally you have to add your own api key.

> We use the OpenAI engine to create a model in MindsDB. Please note that the api_key parameter is optional on [cloud.mindsdb.com](https://cloud.mindsdb.com/register/nlp) but mandatory for local usage/on-premise. You can obtain an OpenAI API key by signing up for OpenAI’s API services on their website. Once you have signed up, you can find your API key in the API Key section of the OpenAI dashboard. You can then pass this API key to the MindsDB platform when creating models.

**Comment by tonymacx86PRO** [comment]
No, i tried via mysql connector and It worked i changed password of my
account for this you don't need API key this cool part, i am from yesterday
working on patched babyagi (freeagi)

**Comment by Hamiltongilpin** [comment]
> 

I'm also looking for local and free autogpt integration if anyone figures it out :)
