### ISSUE TITLE
pinecone pods

### ISSUE THREAD

**Issue by Luka5-A8ram** [Torantulino/Auto-GPT#315]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

have a free acount on pinecone.

### Current behavior 😯

pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Thu, 06 Apr 2023 13:22:58 GMT', 'x-envoy-upstream-service-time': '961', 'content-length': '131', 'server': 'envoy'})
HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.

### Expected behavior 🤔

to work.

### Your prompt 📝

python scripts/main.py

**Comment by Luka5-A8ram** [comment]
> I ran into this too initially. If I remember correctly, what I wound up doing is clicking "upgrade" at app.pinecone.io, then explicitly selecting the free option. It was something weird like that...

In the upgrade page, the starter plan already has the button grayed and written "your plan".

**Comment by jantic** [comment]
Yeah I remember that being the case too. It'd be worth trying what I described, just in case. All sorts of dumb things can happen in software.

**Comment by Luka5-A8ram** [comment]
> Yeah I remember that being the case too. It'd be worth trying what I described, just in case. All sorts of dumb things can happen in software.

![image](https://user-images.githubusercontent.com/126712640/230427473-df08924f-0be7-43ab-b77c-6032483edb4f.png)

where?

**Comment by jantic** [comment]
I might have actually clicked "upgrade" on Standard and then didn't commit.  Sorry my memory is really fuzzy on this. But bottom line is I just screwed around in that plans section and magically it worked without me having to pay for an upgraded plan.

**Comment by Luka5-A8ram** [comment]
> I might have actually clicked "upgrade" on Standard and then didn't commit. Sorry my memory is really fuzzy on this. But bottom line is I just screwed around in that plans section and magically it worked without me having to pay for an upgraded plan.

Sadly I already tried that, and it didn't work for me, I will have to wait for some update. :(

**Comment by furu00** [comment]
same here

**Comment by jantic** [comment]
There's a thread here. Perhaps it'll be helpful:  https://community.pinecone.io/t/request-for-help-he-index-exceeds-the-project-quota-of-1-pods-by-1-pods-upgrade-your-account-or-change-the-project-settings-to-increase-the-quota/971

> If you’re on the free tier you’re limited to having one pod running at a time. So if you already have an index, you’ll need to delete that first before creating a new one.

> If you want to keep both indexes running you can upgrade your plan in the console. Just click Organization then Billing.

**Comment by furu00** [comment]
i found the solution. Delete your index. The script will create its own

> ### Duplicates
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Steps to reproduce 🕹
> 
> have a free acount on pinecone.
> ### Current behavior 😯
> 
> pinecone.core.client.exceptions.ApiException: (400) Reason: Bad Request HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Thu, 06 Apr 2023 13:22:58 GMT', 'x-envoy-upstream-service-time': '961', 'content-length': '131', 'server': 'envoy'}) HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.
> ### Expected behavior 🤔
> 
> to work.
> ### Your prompt 📝
> 
> python scripts/main.py

**Comment by Luka5-A8ram** [comment]
> i found the solution. Delete your index. The script will create its own

It was so simple, and yet I overlooked it, thanks. :)

**Comment by luca-git** [comment]
Cancellin pre-existing index in the pinecone console worked for me. On the free plan we are only allowe one. No need to create a new index, it's automatically done. (you may have to run twice as you wait for the index to be active)
