### ISSUE TITLE
Pinecone quota error, do we need a paid subscription?

### ISSUE THREAD

**Issue by luca-git** [Torantulino/Auto-GPT#333]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When running the latest pull and updating .env I get :

HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Thu, 06 Apr 2023 16:48:44 GMT', 'x-envoy-upstream-service-time': '1228', 'content-length': '131', 'server': 'envoy'})
HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by luca-git** [comment]
Duplicate, sorry

**Comment by Utsaww** [comment]
How to resolve this ?
