### ISSUE TITLE
FIXED: execute_code Not working in Visual Studio / Powershell / CMD

### ISSUE THREAD

**Issue by emskiemre** [Torantulino/Auto-GPT#337]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Writes a simple test.py script to it's working directory that would print "Hello World"

File is inside working directory as seen in file explorer or Visual Code.

But when it tries to run the execute_code command it returns with the following error:

API error and File not found ....

By inspecting the execute_code.py script i see this:

import docker
import os

def execute_python_file(file):
    workspace_folder = "auto_gpt_workspace"

    print (f"Executing file '{file}' in workspace '{workspace_folder}'")

    if not file.endswith(".py"):
        return "Error: Invalid file type. Only .py files are allowed."

    file_path = os.path.join(workspace_folder, file)

    if not os.path.isfile(file_path):
        return f"Error: File '{file}' does not exist."

    try:
        client = docker.from_env()

        # You can replace 'python:3.8' with the desired Python image/version
        # You can find available Python images on Docker Hub:
        # https://hub.docker.com/_/python
        container = client.containers.run(
            'python:3.10',
            f'python {file}',
            volumes={
                os.path.abspath(workspace_folder): {
                    'bind': '/workspace',
                    'mode': 'ro'}},
            working_dir='/workspace',
            stderr=True,
            stdout=True,
            detach=True,
        )

        output = container.wait()
        logs = container.logs().decode('utf-8')
        container.remove()

        # print(f"Execution complete. Output: {output}")
        # print(f"Logs: {logs}") 

        return logs

    except Exception as e:
        return f"Error: {str(e)}"

Not sure if i need dockr installed or something ?

### Current behavior 😯

Read above.

### Expected behavior 🤔

Executing and testing the script it wrote.

### Your prompt 📝

```yaml
# Paste your prompt here

Read above

**Comment by sullyo** [comment]
Yep noticing this as well. Its actually able to write the code to the file and update it, but when it runs it always just says 
`Command execute_python_file returned: Error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

**Comment by emskiemre** [comment]
But what does that mean, like which API ? ...

**Comment by emskiemre** [comment]
PLAN: 
-  Use the execute_python_file command to execute the Python program saved as test.py
-  Verify if the program has executed without any errors or issues
CRITICISM: None
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'test.py'}
Executing file 'test.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the specified file.')

**Comment by emskiemre** [comment]
> Yep noticing this as well. Its actually able to write the code to the file and update it, but when it runs it always just says `Command execute_python_file returned: Error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

You need docker installed my friend:

the script will not work without Docker installed. The script relies on the Docker API to run the Python program inside a Docker container. If Docker is not installed, the script will fail to execute the program. "GPT4" 💯

**Comment by emskiemre** [comment]
The script relies on the Docker API to run the Python program inside a Docker container. If Docker is not installed, the script will fail to execute the program.

**Comment by tlnet1981** [comment]
> 

Hi basically this is working with docker (Big thanks!) , but: It seems that in docker the python modules needed are not installed. So my AutoGPT checks if pandas is installed:

NEXT ACTION:  COMMAND = evaluate_code ARGUMENTS = {'code': 'import sys\n!{sys.executable} -m pip install pandas_datareader'}
SYSTEM:  Command evaluate_code returned: ['Requirement already satisfied: pandas_datareader in /usr/local/lib/python3.7/dist-packages (0.9.0)', 'Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (1.1.5)', 'Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (4.2.6)', 'Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas_datareader) (2.23.0)', 'Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from
 pandas>=0.23->pandas_datareader) (1.19.5)', 'Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas_datareader) (2018.9)', 'Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas_datareader) (2.8.2)', 'Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.15.0)']
 
 but when running the file, it doesnt find the module, any ideas?
 
 NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'dlstocks.py'}
Executing file 'dlstocks.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Traceback (most recent call last): File "/workspace/dlstocks.py", line 2,
 in <module> import pandas_datareader as pdr ModuleNotFoundError: No module named 'pandas_datareader'
