### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jasonmhead** [Torantulino/Auto-GPT#35]
Would it be possible to MIT license this repo to fully open up potential for use with opensource language models?

**Comment by Torantulino** [comment]
Done!

**Comment by shoyer** [comment]
The MIT license seems inconsistent with the project README, which currently states:

> By using Auto-GPT, you agree to indemnify, defend, and hold harmless the developers, contributors, and any affiliated parties from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from your use of this software or your violation of these terms.

**Comment by jasonmhead** [comment]
Request: could we get the above mentioned user liability text removed from the README?

A disclaimer of any responsibility of use should be harmless, and all further user obligations could be removed.
