### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by simoanorak** [Torantulino/Auto-GPT#379]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Have followed the installation guide. using macOS Ventura 13.3

ran pip3 install -r requirements.txt

didnt run continuous mode
didn;t run chatgpt 3.5 only

### Current behavior 😯

when i run python scripts/main.py 

i get

Traceback (most recent call last):
  File "/Users/rich/Documents/Auto-GPT-master/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/Users/rich/Documents/Auto-GPT-master/scripts/commands.py", line 1, in <module>
    import browse
  File "/Users/rich/Documents/Auto-GPT-master/scripts/browse.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### Expected behavior 🤔

would expect the prompt to appear

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by rowbot1** [comment]
try running

`pip3 install requests`

**Comment by richbeales** [comment]
Also, make sure you don't have more than one version of Python installed (or if you do, you have called "pip" on the right one)

**Comment by simoanorak** [comment]
thanks for the comments. i may have installed python more than once.

with the above command run from 
rich@Richards-MacBook-Pro Auto-GPT-master % pip3 install requests
i get
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests) (2022.12.7)

is there a way to tidy this up? / resolve this?

**Comment by simoanorak** [comment]
python3 scripts/main.py
resolved it. thanks for your help guys, have a great day

**Comment by rowbot1** [comment]
You can use the `pip3 freeze` command to list all packages that you have installed and their versions. This command will output the list of installed packages in a clean and organised format. This will make it easier to identify any packages that need to be updated or installed.

**Comment by SebastianSala** [comment]
Had this error. Uninstalled latest version of Python and installed 3.10, then it worked.

**Comment by koltregaskes** [comment]
I had multiple Python installed for 311, 310 and 39.  I need these for other repos but I went to Advanced Setting in Windows, Environment Variables, selected Edit on Path then reordered to have 311 folders at the top, then 310 then 39.  It worked after that.

**Comment by drumstick90** [comment]
if you'r using python3:
pip3 install -r- requirements.txt
