### ISSUE TITLE
Error: Invalid JSON

### ISSUE THREAD

**Issue by cometbus** [Torantulino/Auto-GPT#40]
I'm getting this argument in a loop

NEXT ACTION:  COMMAND = Error: ARGUMENTS = Invalid JSON
SYSTEM:  Command Error: returned: Unknown command Error:
Error: Invalid JSON

**Comment by Taytay** [comment]
Looks like a bug in what is getting sent to the AI:
```
Goal 3:
------------ CONTEXT SENT TO AI ---------------
System: Permanent memory: []
User: NEXT COMMAND
----------- END OF CONTEXT ----------------
assistant reply: What would you like me to do?
Error: Invalid JSON
 What would you like me to do?
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Invalid JSON
Enter 'y' to authorise command or 'n' to exit program...
Input:
```

**Comment by altryne** [comment]
Same with default run

**Comment by adustyugov** [comment]
some problems with escaping in string values. looks like due to prompts(initial or generated ones). we should add checks and escaping for strings

**Comment by cometbus** [comment]
example, if you require a Google Search, please provide the following command: ``` { "command": { "name": "google", "args": { "input": "<search>" } } } ``` For executing a Python file, you can issue the command: ``` { "command": { "name": "execute_python_file", "args": { "file": "<file>" } } } ``` If you have any questions or require assistance with a particular command or task, please don't hesitate to ask.
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Invalid JSON
SYSTEM:  Command Error: returned: Unknown command Error:

**Comment by anslex** [comment]
gpt-3.5-turbo
Python 3.11.2
commit 64af11f4ab9b4fe5e6813a3cbe3d343a1f1b5c98

File is present in 'auto_gpt_workspace'

`python scripts/main.py speak-mode
`
and error still there:
```
Goal 1: read file 'main.py'
Goal 2: 
Error: Prompt file not found
Error: Invalid JSON
 What is the path or location of the 'main.py' file that you want me to read? Is it in the same directory as this program or is it in a different location?
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Invalid JSON
```

**Comment by renner-c** [comment]
Solution here:
https://github.com/Torantulino/Auto-GPT/issues/21#issuecomment-1493458050
