### ISSUE TITLE
Having issues setting up pinecone

### ISSUE THREAD

**Issue by zacgibson21** [Torantulino/Auto-GPT#405]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Fri, 07 Apr 2023 16:51:26 GMT', 'x-envoy-upstream-service-time': '1171', 'content-length': '131', 'server': 'envoy'})
HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.

### Current behavior 😯

I am not too sure what I am doing wrong here. I think I may have made a mistake setting up the index in pinecone? Does anyone have any suggested settings for pinecone or any other ideas what may be causing this issue?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Nnnsightnnn** [comment]
This error is likely due to using the free version of Pinecone.  It limits you.  Simply delete the existing index.  Keep in mind that it takes about 5-10 minutes to initialize a new index so Auto-GPT won't be able to utilize the new index immediately after running the main.py again.

**Comment by zacgibson21** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/8262174/230653061-74084b62-6fbb-4fa7-af42-767506e3f486.png">


Which of these settings do you recommend?

**Comment by zacgibson21** [comment]
marking closed. I realized i should not be setting up the index manually as autoGPT sets it up with the api. Thank you.
