### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by ybleiel** [Torantulino/Auto-GPT#432]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python3 scripts/main.py

### Current behavior 😯

python3 scripts/main.py --gpt3only
Traceback (most recent call last):
  File "/Users/yb/auto-gpt/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/Users/yb/auto-gpt/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/Users/yb/auto-gpt/Auto-GPT/scripts/browse.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### Expected behavior 🤔

the program should start

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by thedotmack** [comment]
I'm getting the same issue

**Comment by eyejake** [comment]
same

**Comment by Ash16-4** [comment]
same

**Comment by timeXway** [comment]
same "ModuleNotFoundError: No module named 'requests'"
anyone knows how to fix it yet?

**Comment by ybleiel** [comment]
try pip3 install request

**Comment by SebastianSala** [comment]
Had this error. Uninstalled latest version of Python and installed 3.10, then it worked.

**Comment by koltregaskes** [comment]
Yes I have this same error.

**Comment by koltregaskes** [comment]
Fixed this, see here for other thread on this: https://github.com/Torantulino/Auto-GPT/issues/379 

I had multiple Python installed for 311, 310 and 39.  I need these for other repos but I went to Advanced Setting in Windows, Environment Variables, selected Edit on Path then reordered to have 311 folders at the top, then 310 then 39.  It worked after that.
