### ISSUE TITLE
Grant capability to label bugs as such

### ISSUE THREAD

**Issue by nponeccop** [Torantulino/Auto-GPT#469]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Many of the issues aren't defects. I'm willing to help you by marking bugs as such in the tracker using labels. I will only add "bug" labels to bug reports at the moment so you see my capability and I don't disrupt anything. 

But ATM I lack permissions.

### Examples 🌈

This same issue is hard to separate from bugs

### Motivation 🔦

The project is poorly managed and there are many types of reports lumped to gether. I can help with the project organization.

**Comment by richbeales** [comment]
I have reached out to @Torantulino to see if he's willing to grow the number of people with some kind of write access to the github repo so more people can help out.

**Comment by nponeccop** [comment]
I wonder if we can setup a secondary repo of a sort where we can merge all pull requests @Torantulino approves. So that we help and it's safe in the sense that we can't do harm. I guess with the 13k stars he woke up a celebrity overnight and it's hard for him to manage it all in all senses, including both technical and personal.

**Comment by richbeales** [comment]
Or just an experimental branch, with different push permissions.  It's very early days with lots of people keen to contribute.  I'm sure it's something he's thinking about.

**Comment by Artemonim** [comment]
I have no experience with **so** popular and active repositories, but I have participated as Issue Wathcer in several open-source games and set up a lable system for them. It really helps a lot.
![2023-04-11_19-43-10](https://user-images.githubusercontent.com/36363466/231232498-d8e97f74-9060-4bfc-beb1-63e1df37004d.png)

We don't need additional repositories or branches to do this, but we will have to trust people who join the team 🙂

**Comment by richbeales** [comment]
This is now in hand.  @Torantulino has started a small team of collaborators and we will be working on this going foward.

**Comment by Artemonim** [comment]
@richbeales I recommend using emoji in the labels - the eye is immediately attracted to them and it also makes tags more unique.
