### ISSUE TITLE
Could we please have a Discord?

### ISSUE THREAD

**Issue by p-i-** [Torantulino/Auto-GPT#47]
If there's some intention to encourage community effort in this project, a Discord would be most welcome.

I've been looking at similar ideas (GPT4-assisted AI operating over Dockerized Linux system).

**Comment by rmn1978** [comment]
It would be great!

**Comment by alexisneuhaus** [comment]
Would love a Discord!  This is awesome!

**Comment by Torantulino** [comment]
Okay, that sounds good to me, I'll set one up.

**Comment by beyondpremiere** [comment]
YEEES! This is an exciting exciting project, can't sleep now

**Comment by alelordelo** [comment]
+1 !

**Comment by Torantulino** [comment]
https://discord.gg/PQ7VX6TY4t 🚀🚀

**Comment by athabasca** [comment]
The invite links here and twitter don't work--maybe they expired?

**Comment by BillSchumacher** [comment]
> The invite links here and on twitter don't work--maybe they expired?

Try discord.gg/autogpt

**Comment by richbeales** [comment]
marking as closed.

**Comment by athabasca** [comment]
> > The invite links here and on twitter don't work--maybe they expired?
> 
> Try discord.gg/autogpt

Is the link configured to deny newer accounts? I wanted to join with my recent AI dev account but could only join with my old main.

**Comment by gebeer** [comment]
Also cannot join using discord.gg/autogpt
> Unable to accept invite

**Comment by jclicky** [comment]
Same, unable to accept invite. Looks like the link on @SigGravitas' [Twitter profile](https://twitter.com/siggravitas):
<img width="488" alt="Screen Shot 2023-04-16 at 8 04 50 PM" src="https://user-images.githubusercontent.com/63612868/232368173-8eb769da-22dc-45ff-90d8-314efeaad13e.png">

**Comment by mikeyang01** [comment]
link expired，unable to join
