### ISSUE TITLE
AutoGPT as extra developer

### ISSUE THREAD

**Issue by theobouwman** [Torantulino/Auto-GPT#474]
I was wondering if it is possible to use this to create an extra cloud AI developer like this:
- Create Tasks in GitHub with detailed descriptions 
- trigger the AI bot to create an extra branch to write the code to complete the task (like adding a new api crud route etc)
- let it commit those changes
- let it create a pull request for human check
- trigger the bot to update the pull request with the comments made but human developers

This is possible to write right?

Thanks in advance.

**Comment by dysai1234** [comment]
This would be really crazy . I wonder What the prompt would be

**Comment by theobouwman** [comment]
Let the project for instance be a stock Laravel application. By making the tasks really specific it should be able to make small incremental changes right? And the main requirement for the system would be to index and understand the code base
