### ISSUE TITLE
Pinecone limit

### ISSUE THREAD

**Issue by HoussenMoshine** [Torantulino/Auto-GPT#480]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I'm getting a error related to pinecone quota limit. Bunch of errors message and at the end, I have :

`HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.`

It's stated that even the free plan of Pinecone, but it's not working.  And what the value of "dimensions" field in the index of Pinecone.

### Current behavior 😯

script can run

### Your prompt 📝

```yaml
Don't see the file
```

**Comment by richbeales** [comment]
Don't create the index yourself in pinecone, let AutoGPT do it for you.
Delete anything in pinecone and start the app again.

**Comment by HoussenMoshine** [comment]
Oh thanks ! I've misunderstood this step. It work now !
