### ISSUE TITLE
Pillow missing from requirements.txt

### ISSUE THREAD

**Issue by Q-efx** [Torantulino/Auto-GPT#493]
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
duplicate of https://github.com/Torantulino/Auto-GPT/issues/481

**Comment by BogNogga** [comment]
pip install Pillow

**Comment by richbeales** [comment]
Will be solved by https://github.com/Torantulino/Auto-GPT/pull/482
