### ISSUE TITLE
Auto-GPT and Pinecone [!!use extreme caution!!]

### ISSUE THREAD

**Issue by aalbrightpdx** [Torantulino/Auto-GPT#502]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I experimented with Auto-GPT and Pinecone over the course of 2-4 days (I used Auto-GPT maybe 5x for 20 min at a time) and Pinecone wanted to charge me $120.00 for the use of their "services".

If you use Pinecone use extreme caution they are extremely shockingly expensive.

They did refund my account, but they also said they wouldn't do it again and I should take care when using their service.

Don't use pinecone!! We need a far better alternative.

Response email from Pinecone:

"Thank you for using Pinecone with AutoGPT. Pinecone is not affiliated with AutoGPT. While AutoGPT clears the data in your Pinecone index after every session, it unnecessarily leaves the index service running. Consequently, you have used an extensive amount of cloud resources through Pinecone. 

Your payment was refunded. Unfortunately, we would not be authorised to repeat such a refund again, so we request that you use the service more carefully in the future. 

Best,Pinecone's support team "

### Current behavior 😯

"Thank you for using Pinecone with AutoGPT. Pinecone is not affiliated with AutoGPT. While AutoGPT clears the data in your Pinecone index after every session, it unnecessarily leaves the index service running. Consequently, you have used an extensive amount of cloud resources through Pinecone. 

Your payment was refunded. Unfortunately, we would not be authorised to repeat such a refund again, so we request that you use the service more carefully in the future. 

Best,Pinecone's support team "

### Expected behavior 🤔

"Thank you for using Pinecone with AutoGPT. Pinecone is not affiliated with AutoGPT. While AutoGPT clears the data in your Pinecone index after every session, it unnecessarily leaves the index service running. Consequently, you have used an extensive amount of cloud resources through Pinecone. 

Your payment was refunded. Unfortunately, we would not be authorised to repeat such a refund again, so we request that you use the service more carefully in the future. 

Best,Pinecone's support team "

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by mpcahn** [comment]
I keep it on the free tier and it burned through it when I was on my free instance. We need a way to spin up a local vector database on our own hard drive and have Auto-GPT use that rather than an api.

**Comment by sanesanyo** [comment]
Chroma can be a good alternative in this case as we can run it locally.

**Comment by DavidMCampbell** [comment]
Why was Pinecone chosen in the first place? There is **no good reason to store a vector database in the cloud** when it is much more efficient and free to use local storage.

**Comment by pmb2** [comment]
Agreed, do we have any PR's currently working on a localized vector storage solution?

**Comment by copeugne** [comment]
I don't think there's anyone working on this right now

**Comment by Torantulino** [comment]
Working on fixing this right now, hang tight.

**Comment by MikolajMNK19** [comment]
> Working on fixing this right now, hang tight.

Will you potentially add a local vector database implementation for those of us who don't want to use pinecone?

**Comment by MikolajMNK19** [comment]
Also pinecone seems to be having issues right now as im not able to use the api

**Comment by BrianJM** [comment]
PostgreSQL, using [pgvector](https://github.com/pgvector/pgvector), would be a nice addition.

**Comment by Torantulino** [comment]
Fixed this in #372 

Will work more on pinecone specifically at a later date, but for now it's very optional and not the default.

**Comment by santiadavani** [comment]
Check out PostgresML for an open-source vector database alternative - https://github.com/postgresml/postgresml#vector-database
