### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Mr3rr0rz** [Torantulino/Auto-GPT#515]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "/home/unowho/Auto-GPT/scripts/main.py", line 291, in <module>
    mem.permanent_memory,
AttributeError: module 'memory' has no attribute 'permanent_memory'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
Are you running the latest code from git?
main.py line 291 is empty.

**Comment by Mr3rr0rz** [comment]
richbeales was correct git had updated Cheers!
