### ISSUE TITLE
Seems stuck right out of the gate.

### ISSUE THREAD

**Issue by KnobleSavage** [Torantulino/Auto-GPT#522]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Try to run the main python script.  It becomes unresponsive once the goals are filled out.  Allowed it to sit for 10 minutes... never got anything.

C:\autogpt\Auto-GPT>python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: PromptGetterAI
PromptGetterAI here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
PromptGetterAI is: A AI desgined to search the web for interesting stable diffusion prompts and save them to a file locally.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Search for popular image generation prompts suitable for automatic1111 stable diffusion.
Goal 2: collect examples of those prompts and store them locally.
Goal 3: shut down
Goal 4:

### Current behavior 😯

nothing

### Expected behavior 🤔

something

### Your prompt 📝

C:\autogpt\Auto-GPT>python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: PromptGetterAI
PromptGetterAI here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
PromptGetterAI is: A AI desgined to search the web for interesting stable diffusion prompts and save them to a file locally.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Search for popular image generation prompts suitable for automatic1111 stable diffusion.
Goal 2: collect examples of those prompts and store them locally.
Goal 3: shut down
Goal 4:

**Comment by williamp0044** [comment]
Same issue. Set 5 goals. Enter, and then nothing.

**Comment by ChrisRedfield126** [comment]
Same for me as well.  No log but I suspect something with pinecone. I see index created then initiazing and nothing more. Not sure anyway

**Comment by mdmrs** [comment]
> Same for me as well. No log but I suspect something with pinecone. I see index created then initiazing and nothing more. Not sure anyway

same

**Comment by eugenbg** [comment]
same.. seems it's getting stuck when it tries to reach pinecone

**Comment by locodarwin** [comment]
Yep same.

**Comment by micahsgilbert** [comment]
I also had this issue, and for me it was fixed by making sure that the values for `PINECONE_API_KEY` and `PINECONE_ENV` were in quotes.

**Comment by eugenbg** [comment]
didn't help me.. maybe pinecone blocked the requests somehow because of this
https://github.com/Torantulino/Auto-GPT/issues/502

**Comment by locodarwin** [comment]
> didn't help me.. maybe pinecone blocked the requests somehow because of this #502

That's my guess - too many people trying this out on Pinecone with the free plan...I would imagine if I were Pinecone I'd be wanting to block or restrict the heavy incoming load.

**Comment by gdj0nes** [comment]
I'm on @pincone-io team. We have been working with the maintainers to implement a solution #372. We are having trouble with the load in certain environments. You can check the status [here](status.pinecone.io)

**Comment by eugenbg** [comment]
i had to revert to april 4 version to try it out :)

here's the commit i had to rewind to

commit 51e293f64cf17efbbba18965037a8004387945a6 (HEAD -> master)
Author: Toran Bruce Richards <toran.richards@gmail.com>
Date:   Mon Apr 3 15:46:46 2023 +0100

    Adds --gpt3only mode!

**Comment by KnobleSavage** [comment]
> i had to revert to april 4 version to try it out :)
> 
> here's the commit i had to rewind to
> 
> commit [51e293f](https://github.com/Torantulino/Auto-GPT/commit/51e293f64cf17efbbba18965037a8004387945a6) (HEAD -> master) Author: Toran Bruce Richards [toran.richards@gmail.com](mailto:toran.richards@gmail.com) Date: Mon Apr 3 15:46:46 2023 +0100
> 
> ```
> Adds --gpt3only mode!
> ```

Can you give the appropriate git command for someone unfamiliar with git?  I tried copying the command above, but got my cmd shell doesn't recognize "commit" as a command".

**Comment by eugenbg** [comment]
this is not relevant anymore, the newer version is working with local memory just fine.. the issue can be closed

**Comment by KnobleSavage** [comment]
Pulled updates but now getting a different bug.  Closing this issue and opening https://github.com/Torantulino/Auto-GPT/issues/593.
