### ISSUE TITLE
Should write_to_file also create the directory if it doesn't exist?

### ISSUE THREAD

**Issue by kennethgoodman** [Torantulino/Auto-GPT#55]

**Comment by yousefissa** [comment]
Is that not done here, or is the code failing elsewhere?

https://github.com/Torantulino/Auto-GPT/blob/master/scripts/file_operations.py#L5-L8

**Comment by kennethgoodman** [comment]
That’s only for that directory. Not if GPT wants to write to auto_gpt_workspace/foo/bar.pySent from my iPhoneOn Apr 3, 2023, at 1:24 AM, Yousef Issa ***@***.***> wrote:﻿
Is that not done here, or is the code failing elsewhere?
https://github.com/Torantulino/Auto-GPT/blob/master/scripts/file_operations.py#L5-L8
