### ISSUE TITLE
No Healthy Upstream

### ISSUE THREAD

**Issue by ItsReversePlays** [Torantulino/Auto-GPT#552]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Is this issue happening because my pinecone index is stuck initializing or is it an outside issue? I've been waiting for hours.
![Screenshot 2023-04-08 204315](https://user-images.githubusercontent.com/96661575/230753050-3e8f0c5f-63a3-4727-bfcb-553e1750aa12.png)
![image](https://user-images.githubusercontent.com/96661575/230753060-e73d2ec0-4191-4234-b942-af29c93cdafa.png)

### Current behavior 😯

no healthy upstream failure

### Expected behavior 🤔

Running properly

### Your prompt 📝

```yaml
# Paste your prompt here
```s

**Comment by Abhinavchamallamudi** [comment]
Looks like they have issues at their end - https://status.pinecone.io/

```

> Index initialization slow in northamerica-northeast1-gcp
> New index creation issues in eu-west1-gcp

```

**Comment by ItsReversePlays** [comment]
> Looks like they have issues at their end - https://status.pinecone.io/
> 
> ```
> 
> > Index initialization slow in northamerica-northeast1-gcp
> > New index creation issues in eu-west1-gcp
> ```

I just want to do some tests lol

**Comment by Torantulino** [comment]
We now support 2 more options for memory, Pinecone is no longer a requirement.
