### ISSUE TITLE
I just configured role and goals. I'm getting this error.

### ISSUE THREAD

**Issue by pmdnawaz1** [Torantulino/Auto-GPT#570]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

`Using memory of type: PineconeMemory
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
\ Thinking...`

### Your prompt 📝

```yaml
I've not promted anything.
```

**Comment by richbeales** [comment]
Have you added your billing (card) details to OpenAI?

**Comment by Torantulino** [comment]
I've had this occasionally happen, have you tried just re-launching @pmdnawaz1?

**Comment by pmdnawaz1** [comment]
@richbeales Thanks man. I haven't added I'll add and try. @Torantulino did couple of times ^^. Thanks for reply.
