### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by Suryatejakalapala** [Torantulino/Auto-GPT#584]
Using memory of type: LocalCache
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
| Thinking...

**Comment by richbeales** [comment]
Do you have a credit card linked to your OpenAI account?

**Comment by EugeneVanchugov** [comment]
> Do you have a credit card linked to your OpenAI account?

I had the same issue today. 
Linking a credit card solved the issue.

**Comment by Suryatejakalapala** [comment]
> Do you have a credit card linked to your OpenAI account?

Do i need to pay for this? I don't have a credit card any help :///

**Comment by bigkennygz** [comment]
@EugeneVanchugov how long did it take for the issue to resolve? I added a credit card and am still getting the same error trying to rerun just after.

**Comment by Slamsneider** [comment]
You are out of FREE tokens. You will have to wait or read below.

You need to throw your creditcard here: https://platform.openai.com/account/billing/overview and make a $ account for tokens.

Then you can also use the ($) playground. https://platform.openai.com/playground

Remember to set a soft and hard limit or you can loose control of your money spending very quickly.

**Comment by Suryatejakalapala** [comment]
ok thanks
