### ISSUE TITLE
ModuleNotFoundError: No module named 'orjson'

### ISSUE THREAD

**Issue by KnobleSavage** [Torantulino/Auto-GPT#593]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I just did a git pull, after not being able to run see [Issue 522](https://github.com/Torantulino/Auto-GPT/issues/522).
Now I'm getting the following:

 scripts/memory/__init__.py                |  44 +++++++++
 scripts/memory/base.py                    |  31 +++++++
 scripts/memory/local.py                   | 114 ++++++++++++++++++++++++
 scripts/{memory.py => memory/pinecone.py} |  18 +---
 scripts/memory/redismem.py                | 143 ++++++++++++++++++++++++++++++
 13 files changed, 413 insertions(+), 33 deletions(-)
 create mode 100644 scripts/memory/__init__.py
 create mode 100644 scripts/memory/base.py
 create mode 100644 scripts/memory/local.py
 rename scripts/{memory.py => memory/pinecone.py} (80%)
 create mode 100644 scripts/memory/redismem.py

C:\autogpt\Auto-GPT>python scripts/main.py
Traceback (most recent call last):
  File "C:\autogpt\Auto-GPT\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "C:\autogpt\Auto-GPT\scripts\commands.py", line 3, in <module>
    from memory import get_memory
  File "C:\autogpt\Auto-GPT\scripts\memory\__init__.py", line 1, in <module>
    from memory.local import LocalCache
  File "C:\autogpt\Auto-GPT\scripts\memory\local.py", line 2, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

### Current behavior 😯

Crashes when running main.py

### Expected behavior 🤔

Expecting it not to crash.

### Your prompt 📝

```yaml
Not getting this far.
```

**Comment by KnobleSavage** [comment]
Sorry... corrected this one by re-running 
pip install -r requirements.txt

**Comment by ceobitch** [comment]
Hmmm we ran this but still getting same error.
