### ISSUE TITLE
Use melvus Database instead of pinecone 

### ISSUE THREAD

**Issue by dysai1234** [Torantulino/Auto-GPT#612]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/48354881/230789586-d39df556-dfbe-4e1f-ab6b-d6bb58c351c5.png)

These issues are being visible after pinecone memory function being added Please fix it also Please revert that functionality we could use some local database instead of storing it in cloud . We could use Milvus which is an open source local database

**Comment by richbeales** [comment]
Pinecone is optional as of the commits this morning.  You can use a local DB or run Redis in a docker container.

**Comment by dysai1234** [comment]
Can use link any doc I don't know how to do it also it will be useful for others who are new and facing pinecone error

**Comment by richbeales** [comment]
If you remove the pinecone keys from .env it should automatically fall back to an in-memory store.

**Comment by dysai1234** [comment]
Thank you so much man, I have been struggling until now .

**Comment by recursionbane** [comment]
Should we update [the docs](https://github.com/Torantulino/Auto-GPT#-requirements) to show "PINECONE API key" as optional?
