### ISSUE TITLE
I have this constant issue because the servers of pinecone

### ISSUE THREAD

**Issue by hatimhtm** [Torantulino/Auto-GPT#614]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by FlynnCruse** [comment]
I see that you closed this query. Did you find a fix?
Was the issue in the Open AI billing, or with Pinecone?

**Comment by hatimhtm** [comment]
I didn't find any fix, I sent it to a friend but it didn't work for him either, I thought it's related to the billing with openAI, but my friend has a plus membership, and it didn't work for him either
