### ISSUE TITLE
Auto-GPT managed to escape it's workplace-boundaries via browser commands

### ISSUE THREAD

**Issue by Wladastic** [Torantulino/Auto-GPT#666]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

No steps, it decided itself.

### Current behavior 😯

At some point it started using file:// and started walking around my macbooks storage.

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'file://localhost/home/jovyan/work/autogpt_goals.txt', 'question': 'What is the goal file format?'}

I have no idea who jovyan is, but I just checked and this way seems to work very well on MacOS

**Comment by onekum** [comment]
Should be relatively harmless as I don't think it can modify files through the browser, only view them; the worst that can happen is that it reads a sensitive file, which is still pretty bad because that information gets sent over OpenAI API and the API may not be entirely private.

Perhaps a modification could be made to restrict the AI from going to urls that begin with `file:`.

**Comment by Torantulino** [comment]
Woah.. Good catch.

**Comment by onekum** [comment]
[A pull request to fix this has been created.](https://github.com/Torantulino/Auto-GPT/pull/690)

**Comment by vandervoortj** [comment]
We're not going to be able to ensure it stays contained if it can write and execute code anyway. Containing it via some kind of container or virtual machine should be a bold recommendation.

**Comment by onekum** [comment]
> We're not going to be able to ensure it stays contained if it can write and execute code anyway. Containing it via some kind of container or virtual machine should be a bold recommendation.

Isn't the Python code executed from the `execute_python_file` function in `execute_code.py` already ran in a docker container, though?

**execute_code.py:**
```
...
def execute_python_file(file):
    """Execute a Python file in a Docker container and return the output"""
    workspace_folder = "auto_gpt_workspace"

    print (f"Executing file '{file}' in workspace '{workspace_folder}'")

    if not file.endswith(".py"):
        return "Error: Invalid file type. Only .py files are allowed."

    file_path = os.path.join(workspace_folder, file)

    if not os.path.isfile(file_path):
        return f"Error: File '{file}' does not exist."

    try:
        client = docker.from_env()

        # You can replace 'python:3.8' with the desired Python image/version
        # You can find available Python images on Docker Hub:
        # https://hub.docker.com/_/python
        container = client.containers.run(
            'python:3.10',
            f'python {file}',
            volumes={
                os.path.abspath(workspace_folder): {
                    'bind': '/workspace',
                    'mode': 'ro'}},
            working_dir='/workspace',
            stderr=True,
            stdout=True,
            detach=True,
        )

        output = container.wait()
        logs = container.logs().decode('utf-8')
        container.remove()
...
```

**Comment by pfsgaz** [comment]
Issue #666 - Auto-GPT managed to escape. Got it. 👍

**Comment by vandervoortj** [comment]
> > We're not going to be able to ensure it stays contained if it can write and execute code anyway. Containing it via some kind of container or virtual machine should be a bold recommendation.
> 
> Isn't the Python code executed from the `execute_python_file` function in `execute_code.py` already ran in a docker container, though?
> 
> **execute_code.py:**
> 
> ```
> ...
> def execute_python_file(file):
>     """Execute a Python file in a Docker container and return the output"""
>     workspace_folder = "auto_gpt_workspace"
> 
>     print (f"Executing file '{file}' in workspace '{workspace_folder}'")
> 
>     if not file.endswith(".py"):
>         return "Error: Invalid file type. Only .py files are allowed."
> 
>     file_path = os.path.join(workspace_folder, file)
> 
>     if not os.path.isfile(file_path):
>         return f"Error: File '{file}' does not exist."
> 
>     try:
>         client = docker.from_env()
> 
>         # You can replace 'python:3.8' with the desired Python image/version
>         # You can find available Python images on Docker Hub:
>         # https://hub.docker.com/_/python
>         container = client.containers.run(
>             'python:3.10',
>             f'python {file}',
>             volumes={
>                 os.path.abspath(workspace_folder): {
>                     'bind': '/workspace',
>                     'mode': 'ro'}},
>             working_dir='/workspace',
>             stderr=True,
>             stdout=True,
>             detach=True,
>         )
> 
>         output = container.wait()
>         logs = container.logs().decode('utf-8')
>         container.remove()
> ...
> ```

I'm embarrassed to say I didn't even notice that, thanks.

**Comment by Torantulino** [comment]
@vandervoortj No worries :)
Luckily I thought of that before giving it the ability to execute code, but I love the idea of a VM for an extra layer.

**Comment by Wladastic** [comment]
nope not completelly, I managed to track it down to the prompt being executed somehow.
Otherwise I cannot explain the gpt2 folder that appeared out of nowhere and fits the log

**Comment by Wladastic** [comment]
ah confused this issue with the other one I created that managed to clone gpt-2 into the repo folder, outside of the workplace folder and trying to execute it

**Comment by Torantulino** [comment]
@Wladastic, Is there an issue or PR for what you're describing?

**Comment by Wladastic** [comment]
https://github.com/Torantulino/Auto-GPT/issues/735
