### ISSUE TITLE
Recent change broke main.py: NameError: name 'cfg' is not defined

### ISSUE THREAD

**Issue by blankster** [Torantulino/Auto-GPT#669]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

python scripts/main.py --gpt3only

### Current behavior 😯

Traceback (most recent call last):
  File "C:\Users\ND\Documents\Projects\Auto-GPT\scripts\main.py", line 290, in <module>
    check_openai_api_key()
  File "C:\Users\ND\Documents\Projects\Auto-GPT\scripts\main.py", line 22, in check_openai_api_key
    if not cfg.openai_api_key:
NameError: name 'cfg' is not defined

### Expected behavior 🤔

No error

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ian-cannon** [comment]
#672 Does an excellent job of explaining the recreation steps. Can you confirm that this is what you are seeing?

**Comment by ian-cannon** [comment]
https://github.com/Torantulino/Auto-GPT/issues/672 Does an excellent job of explaining the recreation steps. Can you confirm that this is what you are seeing?

**Comment by blankster** [comment]
@ian-cannon I can confirm.
