### ISSUE TITLE
it says there a code error

### ISSUE THREAD

**Issue by DuomaxAE** [Torantulino/Auto-GPT#670]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

It says:
Traceback (most recent call last):
  File "C:\ChatGPT\Auto-GPT\scripts\main.py", line 290, in <module>
    check_openai_api_key()
  File "C:\ChatGPT\Auto-GPT\scripts\main.py", line 22, in check_openai_api_key
    if not cfg.openai_api_key:
NameError: name 'cfg' is not defined
when I do python scripts/main.py after I did all the steps correctly.

**Comment by blankster** [comment]
See also #669

**Comment by blankster** [comment]
This one is fixed in 7547d9bfb161fac31400f7aa3acb8f14e139ee39 and this issue can be closed.
