### ISSUE TITLE
NameError: name 'cfg' is not defined

### ISSUE THREAD

**Issue by akamalov** [Torantulino/Auto-GPT#672]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Version:

```master ee8276c Merge pull request #615 from openaudible/patch-1```
 
Trying to run the program:

```
(base) D:\GPT\Auto-GPT>python scripts\main.py
Traceback (most recent call last):
  File "D:\GPT\Auto-GPT\scripts\main.py", line 290, in <module>
    check_openai_api_key()
  File "D:\GPT\Auto-GPT\scripts\main.py", line 22, in check_openai_api_key
    if not cfg.openai_api_key:
NameError: name 'cfg' is not defined

(base) D:\GPT\Auto-GPT>
```

*File: .env*
```
#PINECONE_API_KEY=your-pinecone-api-key
#PINECONE_ENV=your-pinecone-region
OPENAI_API_KEY="XXXXXXXXXX Edited XXXXXXXXXXXXXXXXXXXX"
#ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL="gpt-4"
FAST_LLM_MODEL="gpt-3.5-turbo"
#GOOGLE_API_KEY=
#CUSTOM_SEARCH_ENGINE_ID=
USE_AZURE=False
#OPENAI_API_BASE=your-base-url-for-azure
#OPENAI_API_VERSION=api-version-for-azure
#OPENAI_DEPLOYMENT_ID=deployment-id-for-azure
```

### Current behavior 😯

Errors out. 

### Expected behavior 🤔

It should run normally

### Your prompt 📝

```
(base) D:\GPT\Auto-GPT>python scripts\main.py

```

**Comment by blankster** [comment]
See also #669 and #670

**Comment by ian-cannon** [comment]
while #669 and #670 Do mention the issue. I would argue that this issue follows the issue template best and should be the issue to handle this

**Comment by jasetom** [comment]
Having the same issue

**Comment by Legit-Ox** [comment]
Same issue.

**Comment by phoebebright** [comment]
Switched order of lines 291/292 and works for me:

     cfg = Config()
     check_openai_api_key()

**Comment by rhod-dev** [comment]
Same.

**Comment by erni-tf** [comment]
before the "def check_openai_api_key()" put  "cfg = Config()" and then it works for me

**Comment by blankster** [comment]
@erni-tf thanks, that worked. Next error is:

Traceback (most recent call last):
  File "C:\Users\ND\Documents\Projects\Auto-GPT\scripts\main.py", line 319, in <module>
    assistant_reply = chat.chat_with_ai(
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

**Comment by Torantulino** [comment]
Fixes in #675

**Comment by erni-tf** [comment]
@blankster did you give the ai 6 goals or did the error spawn after you ran the code?

**Comment by tlnet1981** [comment]
> 

Just 5 goals, the issue appears after the correction of the cfg error

**Comment by i-amgeek** [comment]
@blankster Add `self.debug_mode = False` after `self.debug = False` in scripts/config.py, line :37

**Comment by bealbrown** [comment]
Nullwriter's solution worked for me. Haha, this is from the master branch? Poor guys maintaining this project, so many PR's and little testing ... But still amazing project, thank you!
