### ISSUE TITLE
PRs batch 2

### ISSUE THREAD

**Issue by nponeccop** [Torantulino/Auto-GPT#673]
### Duplicates

- [X] I have searched the existing issues

### Clean Merge Trivial 🌈

- #313
- #574
- #633 - a keyboard Ctrl-C handler
- #637 - a trivial config to use `say` on Macs
- #648 - a trivial config renaming to clarify it's Azure
- #664 - a warning about Google Searches daily quota in Readme
- #674 - a quick fix
- #678
- #688
- #690 
- #702
- #704 
- #706
- #712 
- #714 
- #734

### Clean Merge Not So Trivial

Now these are non-trivial PRs but having all problems resolved.

- #215
- #242 
- #434 
- #685
- #686 - a cleaned up earlier PR
- #697
- #700

### Conflicts
 
- #193 
- #289
- #367 
- #448
- #647 - better path handling

### Question

- #120

### Motivation 🔦

Well, Batch 1 was a success. This batch is ready now, and #709 is WIP

**Comment by Aopenz** [comment]
AttributeError: module 'chat' has no attribute 'chat_with_ai'

**Comment by nponeccop** [comment]
Wrong chat?

**Comment by Aopenz** [comment]
/Auto-GPT/scripts/main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^
AttributeError: module 'chat' has no attribute 'chat_with_ai'

when i use GPT3.5 Only Mode...

**Comment by Aopenz** [comment]
And found that GTP3.5 optimization is not particularly good, always in a dead loop. I tried several simple events and ran them consistently more than 100 times without success: 1, create a Twitter account and post the first tweet. 2, write a simple trading script on tradingview. 3, write a best-selling children's story.

**Comment by nponeccop** [comment]
Open a separate issue. @Torantulino clean this up?

**Comment by nponeccop** [comment]
@Torantulino The new batch is ready!

**Comment by nponeccop** [comment]
Ok, the conflicts were resolved:

- #704
- #714

**Comment by nponeccop** [comment]
@Torantulino 3 of the PRs were fixed again. Merge while you are at it :) I'm going to bed.

**Comment by nponeccop** [comment]
@Torantulino can you merge 3 more? They are clean now.

**Comment by nponeccop** [comment]
For those who have been waiting, we are going to start merging again later today. The project suffers from organizational issues and resolving them takes time. We will fix the master and probably organize a stable branch so that many people can always try the last good version and the things like debug breakage won't happen again.

(This is not an official announcement)

**Comment by nponeccop** [comment]
Thank you all! The batch 2 is finally done now. We are testing it in master, and probably will merge into the new stable branch after the initial testing.

The batch 3 is still open, when we start merging the list of PRs in it will be frozen, so the new PRs will get into Batch 4. If your PR is clean but not in the batch yet, tag me I'll come to check and add.

Thanks for everyone who made it possible. @Torantulino @richbeales and pi (I don't know the GitHub username).

**Comment by katmai** [comment]
you guys are awesome. please keep this up. you are great.
