### ISSUE TITLE
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by phoebebright** [Torantulino/Auto-GPT#676]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Addition of parameter , cfg.debug in call     assistant_reply = chat.chat_with_ai(.  in main.py not expected by chat_with_ai.

### Current behavior 😯

Fails with TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by blankster** [comment]
Same problem here

**Comment by tlnet1981** [comment]
same here

**Comment by cryptidv** [comment]
Same here. Additionally there may be a problem with cfg. Additionally when I add an additional positional argument to `chat_with_ai()`, I get the following error:
```sh
(line 67 chat.py
AttributeError: 'Config' object has no attribute 'debug_mode'. Did you mean: 'set_debug_mode'?
```

**Comment by cryptidv** [comment]
> ```shell
> set_debug_mode
> ```

Yea there seem to be a lot of inconsistencies here wow.

**Comment by AADaoud** [comment]
same problem for me too

**Comment by sebreiler2222** [comment]
same problem for me too. 
the suggested sollution isn`t working for me 

"Possible solution:

remove parameter cfg.debug in main line 325
global replace of debug_mode with debug
OR debug with debug_mode!"

any other suggestions?
Error Code: 
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\sebas\OneDrive\Desktop\GPT 2\Auto-GPT\scripts\main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

**Comment by cryptidv** [comment]
This problem should be resolved with commit #695.

Try running:
```sh
git pull
```
To get the latest code, and run the script again.

**Comment by 4i-helpynet** [comment]
After a git pull, the error appear: 
  File "C:\[DIR]\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug_mode:
AttributeError: 'Config' object has no attribute 'debug_mode'. Did you mean: 'set_debug_mode'?

**Comment by cryptidv** [comment]
@4i-helpynet 

Try recloning the repo. Save your .env and any other files you want to keep and `git clone` the repo again.

**Comment by kinance** [comment]
@cryptidv Seeing duplicate debug_mode functions, this pull request https://github.com/Torantulino/Auto-GPT/pull/704 should fix that. Please help review.

**Comment by 4i-helpynet** [comment]
After a simple git pull, the issue still present
((Since other small issues appear at the first clone, I fix that in the code, and didn't have time to clone again from ground, but I'll check soon that too))

**Comment by adevinwild** [comment]
Pulled the `stable` branch and the problem is still here...
