### ISSUE TITLE
TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by fredadun** [Torantulino/Auto-GPT#684]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "C:\Users\xxxx\Auto-GPT\scripts\main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(

TypeError: chat_with_ai() takes 5 positional arguments but 6 were given

**Comment by Torantulino** [comment]
Duplicate of #676
