### ISSUE TITLE
[OSX 13.2.1] No module named 'requests'

### ISSUE THREAD

**Issue by EloiGattet** [Torantulino/Auto-GPT#69]
Hi!
I'm on a Apple silicon Mac, runny 13.2.1.
Tried the proposed installation process:
`git clone https://github.com/Torantulino/Auto-GPT.git
$ cd 'Auto-GPT'
pip3 install -r requirements.txt
mv .env.template .env
nano .env ` -> Filled the API keys and saved

But when I try to run 
`➜  Auto-GPT git:(master) ✗ python3 scripts/main.py`
I get :
> Traceback (most recent call last):
>   File "/Users/eloi/bin/Auto-GPT/scripts/main.py", line 3, in <module>
>     import commands as cmd
>   File "/Users/eloi/bin/Auto-GPT/scripts/commands.py", line 1, in <module>
>     import browse
>   File "/Users/eloi/bin/Auto-GPT/scripts/browse.py", line 1, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'

Any help please?
Thanks!

**Comment by EloiGattet** [comment]
My bad, it my pip install needed an update. 
`python3.11 -m pip install --upgrade pip` 
and 
`pip3 install -r requirements.txt`
solved it

**Comment by taojeee** [comment]
Same problem on Windows 11, upgrading pip and reinstalling requirements doesn't solve it for me. 
Thankful if someone can help.

**Comment by jalyper** [comment]
same problem, proposed solution didn't work for me

**Comment by TimarTimar** [comment]
I also had this issue on my machine. 

Was able to run it in docker.

```
FROM python:3.11

WORKDIR /app
COPY scripts/ /app
COPY requirements.txt /app
COPY .env /app

RUN pip install -r requirements.txt

CMD ["python", "main.py"]
```

1. `docker build -t myapp .`

2. `docker run -it myapp`

**Comment by taojeee** [comment]
Took me a while to get docker to run, but now it works, thanks!

**Comment by darrentmorgan** [comment]
> 2\. docker run -it myapp

This helped alot, thankyou

**Comment by 0oShaKao0** [comment]
When I try to run "python -m autogpt"
I get:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bruceyu/Auto-GPT/autogpt/__main__.py", line 3, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

Any help please?
Thanks!

**Comment by isky123** [comment]
> 

same question
