### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'debug_mode'

### ISSUE THREAD

**Issue by amit9021** [Torantulino/Auto-GPT#692]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Using memory of type: LocalCache
Traceback (most recent call last):
  File "scripts/main.py", line 318, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug_mode:
AttributeError: 'Config' object has no attribute 'debug_mode'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Torantulino** [comment]
on it

**Comment by Torantulino** [comment]
Fixed in #694

**Comment by Torantulino** [comment]
Fixed in #695
