### ISSUE TITLE
Incorporate agent toolkits from langchain

### ISSUE THREAD

**Issue by claysauruswrecks** [Torantulino/Auto-GPT#7]
https://python.langchain.com/en/latest/modules/agents/toolkits.html

**Comment by dschonholtz** [comment]
Yohei over on Twitter recently torched all of the lang chain agent work to slim down the code. 
In theory the reAct framework will give better results but I think a version of that is currently running here. 

What specifically would the goal of incorporating agents from lang chain accomplish?

**Comment by claysauruswrecks** [comment]
@dschonholtz - Sorry, I'm not following. I opened this issue early in the project's existence. Can you link the changes you're talking about?

**Comment by dschonholtz** [comment]
I was referring to a separate project where a dev pointed out that they could make their project a lot more lean by ripping out lang chain. 
I just wanted to ask what the intended value add was for adding lang chain agents was before they get pulled in. 
ReAct agents or some of the other langchain agents have been shown to perform well. But it would be good to identify why we want to add them before we pull them in over the current system that works fairly well considering it might add bloat without performance improvement

**Comment by ryanpeach** [comment]
Think it's very premature to say "wont-fix" on langchain. Lanchain adds the ability to add tools from large pre-built toolkits, integrate other LLMs, and switch to other prompting styles via it's [AGENT_TYPE](https://python.langchain.com/en/latest/_modules/langchain/agents/agent_types.html#AgentType) enum. 

Not using it is basically the equivalent of announcing you plan to not keep up with the latest open source contributions and research in LLMs.
