### ISSUE TITLE
Not recognising OpenAI API, or not reading .ENV

### ISSUE THREAD

**Issue by JimiVex** [Torantulino/Auto-GPT#784]
Hey there, any time I run main.py, it gives me this message:

"Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys"

I have input the API correctly, and tried it with a new one since, with the same result. Otherwise, I have removed "template" from the .ENV file. Below is what's contained in my .ENV, with most of the APIs obviously censored - but trust, they are entered correctly.

PINECONE_API_KEY=c..........24e2
PINECONE_ENV=asia-southeast1-gcp
OPENAI_API_KEY=sk-G........3mbU
ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL=gpt-4
FAST_LLM_MODEL=gpt-3.5-turbo
GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=
USE_AZURE=False
OPENAI_AZURE_API_BASE=your-base-url-for-azure
OPENAI_AZURE_API_VERSION=api-version-for-azure
OPENAI_AZURE_DEPLOYMENT_ID=deployment-id-for-azure
IMAGE_PROVIDER=dalle
HUGGINGFACE_API_TOKEN=
USE_MAC_OS_TTS=False

Otherwise, please find attached a screencap of my Auto-GPT folder.

![Auto-GPT-Error](https://user-images.githubusercontent.com/115734103/231122144-52e88718-af0e-4cf6-9c8b-6b07050a3ce1.png)

**Comment by richbeales** [comment]
Open the folder in VS Code, or use a terminal / command prompt to "dir" the directory to see what it shows

**Comment by JimiVex** [comment]
Thanks for the swift reply Rich. I "dir"'d the directory, this is what it shows:

11/04/2023  10:12    <DIR>          .
11/04/2023  10:12    <DIR>          ..
11/04/2023  10:21               529 .env.template
11/04/2023  01:31    <DIR>          .github
11/04/2023  01:31               220 .gitignore
11/04/2023  01:31               290 ai_settings.yaml
11/04/2023  10:12    <DIR>          auto_gpt_workspace
11/04/2023  01:31             1,765 CONTRIBUTING.md
11/04/2023  01:31               150 Dockerfile
11/04/2023  01:31             1,098 LICENSE
11/04/2023  01:31    <DIR>          outputs
11/04/2023  01:31            16,266 README.md
11/04/2023  01:31               326 requirements.txt
11/04/2023  10:12    <DIR>          scripts
11/04/2023  01:31    <DIR>          tests
               8 File(s)         20,644 bytes
               7 Dir(s)  256,761,806,848 bytes free

**Comment by richbeales** [comment]
You do not have a ".env" file, only the ".env.template".

Using the same command prompt, type

`copy .env.template .env`

**Comment by JimiVex** [comment]
That did the trick. Rich, you are a scholar and a gentleman - thank you kindly for your help.

**Comment by richbeales** [comment]
Thanks, Windows can be a pain with that sort of thing, please close the issue if resolved.

**Comment by reallyvansh** [comment]
Hey guys 
I'm having the same problem right now. I was happy to find the solution here but unfortunately, it didn't work
I'm on Mac and it was doing the same i.e not showing the true extension so I went to the terminal and did "mv .env.template .env".
It changed the extension but the same error still shows up.
<img width="1482" alt="Screenshot 2023-04-11 at 9 34 20 PM" src="https://user-images.githubusercontent.com/80445979/231222513-1418d648-4d80-46e4-b8fc-bd0eb9c9ee57.png">



My env file looks like this:

PINECONE_API_KEY=your-pinecone-api-key
PINECONE_ENV=your-pinecone-region
OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxx
ELEVENLABS_API_KEY=your-elevenlabs-api-key
SMART_LLM_MODEL=gpt-4
FAST_LLM_MODEL=gpt-3.5-turbo
GOOGLE_API_KEY=
CUSTOM_SEARCH_ENGINE_ID=
USE_AZURE=False
OPENAI_AZURE_API_BASE=your-base-url-for-azure
OPENAI_AZURE_API_VERSION=api-version-for-azure
OPENAI_AZURE_DEPLOYMENT_ID=deployment-id-for-azure
IMAGE_PROVIDER=dalle
HUGGINGFACE_API_TOKEN=
USE_MAC_OS_TTS=False

Any idea what could be happening?

**Comment by lcl27** [comment]
Try "get info" command on Mac and uncheck the "hide extension" box on the get info window. You can then delete the extension ".template" and press enter. That worked for me.
