### ISSUE TITLE
debug mode not debug

### ISSUE THREAD

**Issue by taylor-ennen** [Torantulino/Auto-GPT#803]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

attribute in chat.py is not named correctly

### Current behavior 😯

wrong name can't call the attrb on the object

### Expected behavior 🤔

to use the attrb in a  call without error

### Your prompt 📝

```yaml
# Paste your prompt here

**Comment by KixPanganiban** [comment]
Running into the same issue. Pretty much the first thing that pops up when I try to run `main.py`

![CleanShot 2023-04-11 at 20 36 52](https://user-images.githubusercontent.com/2585982/231164369-0ce3fc10-f604-4fe0-bc0b-b02c384477c4.png)

I was able to run it fine this morning, but this started appearing this evening when I pulled from master.

**Comment by mflanagan1041** [comment]
getting the same thing now as well

**Comment by Zanthoxylem** [comment]
Also getting this

**Comment by blankster** [comment]
+1

**Comment by Cralins** [comment]
When i download yesteday i filled all open ai and pine ai.Not work.after just onle open ai  key work.but give another error today i tried again and all fiil things like key work and got debug problem +1 (line 67, in chat_with_ai
    if cfg.debug:    and  AttributeError: 'Config' object has no attribute 'debug'       )    +1

**Comment by jtessler23** [comment]
+1

**Comment by martinussuijkerbuijk** [comment]
You have to change the attribute from `cfg.debug` to `cfg.debug_mode` in L67, 74 and 113.

**Comment by Cralins** [comment]
> You have to change the attribute from `cfg.debug` to `cfg.debug_mode` in L67, 74 and 113.

in the main.py  newbie question

**Comment by farrimus** [comment]
also need to change the name in json_parser.py line 94

**Comment by tlnet1981** [comment]
works with changing the code as suggested Thank you!

**Comment by james431987** [comment]
> You have to change the attribute from `cfg.debug` to `cfg.debug_mode` in L67, 74 and 113.

I replaced cfg.debug to cfg.debug_mode and that worked for getting the program started again

but after a while, while it's running it's throwing

Error:
 Traceback (most recent call last): File "C:\Auto-GPT\scripts\json_parser.py", line 55, in fix_and_parse_json return json.loads(json_str) File "C:\Users\james\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads return _default_decoder.decode(s) File "C:\Users\james\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Users\james\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 154 (char 1095) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Auto-GPT\scripts\main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "C:\Auto-GPT\scripts\json_parser.py", line 63, in fix_and_parse_json ai_fixed_json = fix_json(json_str, JSON_SCHEMA) File "C:\Auto-GPT\scripts\json_parser.py", line 94, in fix_json if cfg.debug: AttributeError: 'Config' object has no attribute 'debug'
 
 
 which seems pretty similar. Any idea where else I might need to change cfg.debug to cfg.debug_mode ?

**Comment by guypayeur** [comment]
I also have this replaced in the json_parser.py. For was line 94   if cfg.debug: -> if cfg.debug_mode:

**Comment by DerekCL** [comment]
For reference, I had to change chat.py, json_parser.py, and json_utils.py.

**Comment by gubatron** [comment]
Same issue here
```
$ python3 scripts/main.py 
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/gubatron/workspace/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/gubatron/workspace/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'
```

**Comment by transcendReality** [comment]
I have changed all necessary lines in chat.py - 67, 74, and 113, and I still get the error. I also changed line 94 in json_parser.py from cfg.debug to cfg.debug_mode, and the issue persists. Am I changing this wrong? I'm just highlighting the text, backspacing, and writing it in. I don't know what it wants me to do on line 321 in main.py

"Traceback (most recent call last):
  File "C:\Users\Bullpin\Downloads\AI\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bullpin\Downloads\AI\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'"

**Comment by szelesaron** [comment]
> I have changed all necessary lines in chat.py - 67, 74, and 113, and I still get the error. I also changed line 94 in json_parser.py from cfg.debug to cfg.debug_mode, and the issue persists. Am I changing this wrong? I'm just highlighting the text, backspacing, and writing it in. I don't know what it wants me to do on line 321 in main.py
> 
> "Traceback (most recent call last): File "C:\Users\Bullpin\Downloads\AI\Auto-GPT\scripts\main.py", line 321, in assistant_reply = chat.chat_with_ai( ^^^^^^^^^^^^^^^^^^ File "C:\Users\Bullpin\Downloads\AI\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai if cfg.debug: ^^^^^^^^^ AttributeError: 'Config' object has no attribute 'debug'"

You still have cfg.debug at L67 in `chat.py` according to the error above.

**Comment by transcendReality** [comment]
They are all changed, it just doesn't recognize that they are changed. Am I supposed to save this somehow?

**Comment by szelesaron** [comment]
> They are all changed, it just doesn't recognize that they are changed. Am I supposed to save this somehow?

Have you saved the file?

**Comment by slavakurilyak** [comment]
To fix the error, you need to add the `debug` attribute to the `Config` class. Add the following line inside the `__init__` method of the `Config` class:

```
self.debug = False
```

This sets the default value of the `debug` attribute to False. You can change this value to True later if you need to enable debug mode. Once you have made this change, save the file and try running the program again.

**Comment by enixlabs** [comment]
> To fix the error, you need to add the `debug` attribute to the `Config` class. Add the following line inside the `__init__` method of the `Config` class:
> 
> ```
> self.debug = False
> ```
> 
> This sets the default value of the `debug` attribute to False. You can change this value to True later if you need to enable debug mode. Once you have made this change, save the file and try running the program again.

Thank you, works perfectly.

**Comment by transcendReality** [comment]
Okay. I wasn't saving but now my new issue is 'API rate limit reached'

**Comment by transcendReality** [comment]
Okay, I guess I'll have to pay them. Thanks.

**Comment by szelesaron** [comment]
> ve to pay them. Thanks.

Please refer to [#815](https://github.com/Torantulino/Auto-GPT/issues/815)

**Comment by szelesaron** [comment]
> Okay. I wasn't saving but now my new issue is 'API rate limit reached'

Please refer to #815

**Comment by hanskraut31312312** [comment]
Traceback (most recent call last):
  File "scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Programming\Auto-GPT_AI_8\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'


me too

**Comment by jokercimi** [comment]
I also getting this error

**Comment by thecookingsenpai** [comment]
dirty working fix (to avoid searching all the files)
`cfg=Config()
cfg.debug = cfg.debug_mode`

**Comment by OannesGPT** [comment]
> > > You have to change the attribute from `cfg.debug` to `cfg.debug_mode` in L67, 74 and 113.
> > 
> > 
> > In which arquive?
> 
> Replace it in `chat.py`

Can confirm that this works. 
I'm still running into a loop where he do_nothing, might be related to sth else. But it worked fine this other day

**Comment by james431987** [comment]
> > > > You have to change the attribute from `cfg.debug` to `cfg.debug_mode` in L67, 74 and 113.
> > > 
> > > 
> > > In which arquive?
> > 
> > 
> > Replace it in `chat.py`
> 
> Can confirm that this works. I'm still running into a loop where he do_nothing, might be related to sth else. But it worked fine this other day

#830 we found a work around for the do_nothing

**Comment by ss5nathan** [comment]
Git checkout 2959bf6f72feafb0e769a51475f93f3994b6f801 to get to a working version.

**Comment by miromistro** [comment]
self.debug = True
        self.debug_mode = True
work for me

**Comment by apylePAD** [comment]
> in config.py, L36?
