### ISSUE TITLE
Wrong debug flag attribute

### ISSUE THREAD

**Issue by omrip1** [Torantulino/Auto-GPT#850]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

in chat.py:74
condition is: "if cfg.debug"
but in config.py the attribute is debug_mode.

------------------------------------------------------------------

> python scripts/main.py --continuous
Continuous Mode:  ENABLED
WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/home/omrip/projects/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/home/omrip/projects/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by richbeales** [comment]
dupe of https://github.com/Torantulino/Auto-GPT/issues/803

**Comment by omrip1** [comment]
Thanks I missed it
