### ISSUE TITLE
Unable to initiate "python scripts/main.py"

### ISSUE THREAD

**Issue by hariikk** [Torantulino/Auto-GPT#860]
### Duplicates

- [ ] I have searched the existing issues

### Steps to reproduce 🕹

In command promt, while initiating with "python scripts/main.py", the below error pops up, i have filled all the api codes necessary, idk what im doing wrong here.

Traceback (most recent call last):
  File "C:\Users\hari\Downloads\auto gpt\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\hari\Downloads\auto gpt\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by kunal-jar** [comment]
Facing the same issue

**Comment by s7wf** [comment]
Same also here

**Comment by s7wf** [comment]
> Figured out the issue
> 
> Line 36 in config.py needs to be
> 
> self.debug = os.getenv("DEBUG_MODE", "False") == "True"

Causes other issues but at least the code runs

**Comment by jcameron-oasis** [comment]
> > Figured out the issue
> > Line 36 in config.py needs to be
> > self.debug = os.getenv("DEBUG_MODE", "False") == "True"
> 
> Causes other issues but at least the code runs

This worked for me, thank you.

**Comment by Slowly-Grokking** [comment]
dupe:
https://github.com/Torantulino/Auto-GPT/issues/803
https://github.com/Torantulino/Auto-GPT/pull/858
https://github.com/Torantulino/Auto-GPT/pull/818
https://github.com/Torantulino/Auto-GPT/pull/835
etc.

https://github.com/Torantulino/Auto-GPT/issues?q=debug

**Comment by highjohnconquer** [comment]
> self.debug = os.getenv("DEBUG_MODE", "False") == "True"

yeah i'm running into a new issue:

SYSTEM:  Command Error: threw the following error: 'Config' object has no attribute 'debug_mode'

**Comment by Slowly-Grokking** [comment]
https://github.com/Torantulino/Auto-GPT/issues/803#issuecomment-1503772590

```
dirty working fix (to avoid searching all the files)
cfg.debug = cfg.debug_mode
Under the line that says cfg=Config() in main.py (at the beginning)
```

if everyone would search for existing issues, it will be much easier to find working solutions, and thus speed up development of this project.    When there are dozen of duplicate issues with even more possible solutions,  it takes ages to merge the new code.

**Comment by richbeales** [comment]
please pull latest from github
