### ISSUE TITLE
can't even start main.py

### ISSUE THREAD

**Issue by nissan62** [Torantulino/Auto-GPT#869]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I fulfilled requirements and followed all the steps from readme.
but when i try to run main.py it gets error:

python scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/home/owl/Music/work/work_env/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/home/owl/Music/work/work_env/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Slowly-Grokking** [comment]
Duplicate:
https://github.com/Torantulino/Auto-GPT/issues/860
https://github.com/Torantulino/Auto-GPT/issues/803
https://github.com/Torantulino/Auto-GPT/pull/858
https://github.com/Torantulino/Auto-GPT/pull/818
https://github.com/Torantulino/Auto-GPT/pull/835
etc.

Search the issues.
https://github.com/Torantulino/Auto-GPT/issues?q=debug

**Comment by richbeales** [comment]
fixed, merged.
