### ISSUE TITLE
On fresh download, Error in new current GitHub Repo 

### ISSUE THREAD

**Issue by theekruger** [Torantulino/Auto-GPT#872]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Error present as of 1630PST April 11th 2023

Open a fresh environment

Open Powershell (as admin if applicable) 

Ensure you are in the correct directory via:
 cd [your path] 
 
 Download repo via git:
 git clone https://github.com/Torantulino/Auto-GPT.git
 
 Then setup requirements in fresh env:
 pip install -r requirements.txt 
 
 Then boot up autogpt instance via:
 
 python scripts\main.py --gpt3only 
 
 (alternatively can also do it without the "--gpt3only" configuration, error is present with speak and with either specification (aka just: python scripts\main.py ))
 
 Error will present:
 
 Using memory of type: LocalCache
Traceback (most recent call last):
  File "[your path], line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File [your path]", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

### Current behavior 😯

It just doesn't load, it kicks these errors, unable to find the "debug" attribute in the "Config" object. 

### Expected behavior 🤔

It should loath the main.py for interfacing with autogpt scripts 

### Your prompt 📝

```yaml
# Paste your prompt here
```

N/A

**Comment by Slowly-Grokking** [comment]
see how your error is listed here:

AttributeError: 'Config' object has no attribute 'debug'

try searching the existing issues for "config" or debug"

Duplicate:
https://github.com/Torantulino/Auto-GPT/issues/860
https://github.com/Torantulino/Auto-GPT/issues/803
https://github.com/Torantulino/Auto-GPT/pull/858
https://github.com/Torantulino/Auto-GPT/pull/818
https://github.com/Torantulino/Auto-GPT/pull/835
https://github.com/Torantulino/Auto-GPT/pull/869
etc.

**Comment by theekruger** [comment]
> see how your error is listed here:
> 
> AttributeError: 'Config' object has no attribute 'debug'
> 
> try searching the existing issues for "config" or debug"
> 
> Duplicate: #860 #803 #858 #818 #835 #869 etc.



You are correct indeed and I just updated the chat.py as per:
https://github.com/Torantulino/Auto-GPT/blob/225ece51146468d84365be2f3918033d10c96bec/scripts/chat.py

I had assumed this wasn't applicable because it was a fix already posted. I didn't realize it wasn't part of the repo, my apologies. Thank you for the nudge in the right direction.

**Comment by Slowly-Grokking** [comment]
> Thank you for the nudge in the right direction.

Awesome!  Happy that I was able to help.

**Comment by richbeales** [comment]
fixed
