### ISSUE TITLE
Using memory of type: LocalCache Traceback error

### ISSUE THREAD

**Issue by Higgins4k** [Torantulino/Auto-GPT#876]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I did a fresh download, repulled from master and any prompt is giving the error below

### Current behavior 😯

Getting this error 
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\Christian\Desktop\AutoGPT\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\Christian\Desktop\AutoGPT\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

### Expected behavior 🤔

It should run with no issue

### Your prompt 📝

```yaml
# Any prompt does this
```

**Comment by dwrtz** [comment]
similar issues https://github.com/Torantulino/Auto-GPT/issues/872#issuecomment-1504282697

**Comment by Higgins4k** [comment]
Ah, will close this I saw that somewhere else but thought pulling would use that version, didn't realize it wasn't accepted yet.
