### ISSUE TITLE
Issue with config.py or .env -- not recognizing api key - - mac

### ISSUE THREAD

**Issue by jennyqueenofswords** [Torantulino/Auto-GPT#881]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

**Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys**

(Saw that this was solved on windows, but the fix didn't work for mac)

I have updated my .env file and confirmed that it has the proper extension. My pinecone and openai api info has been entered. Still getting the error :(

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ardventures** [comment]
I am also getting the same problem

**Comment by arhyneRWU** [comment]
I have it running on my mac.  no issues, 

in the .env file your API key is in quotes and copy and pasted from openai? 

OPENAI_API_KEY="sk-blahblahblahblah"

**Comment by ardventures** [comment]
I didn't have it in quotes, but I just changed it, tried it, and It gave me the same error 
Please set your OpenAI API key in config.py or as an environment variable.
You can get your key from https://beta.openai.com/account/api-keys

**Comment by dwrtz** [comment]
it should work without quotes. Are you running auto-gpt from the project root folder?

should be like this `python scripts/main.py`

if you try to run from inside the scripts folder your .env file wont be found

**Comment by ardventures** [comment]
I am running from the root directory. python3 scripts/main.py --gpt3only

**Comment by mdihay** [comment]
FIXED it by creating a new API key - go to https://platform.openai.com/account/api-keys generate a new key and use it in your .env

**Comment by jennyqueenofswords** [comment]
i tried that twice before i posted my issue, but it didn't work for me.

**Comment by javierpiles** [comment]
same problem as @jennyqueenofswords

**Comment by xuhaoranLeo** [comment]
mv .env.template .env
fix for me!

**Comment by GilesAlonso** [comment]
mv .env.template .env
Worked here also!

**Comment by ardventures** [comment]
I was able to change .env.template to .env in the mac finder. I can still see and open .env in the mac finder. However, when I am in the terminal I can't even see the .env file. 

I even tried defaults write com.apple.finder AppleShowAllFiles -bool true to be able to see hidden files and I still can't see .env in the terminal window

**Comment by javierpiles** [comment]
> @jennyqueenofswords is this resolved now (it's almost always because .env doesn't exist)?

in my case, yes. I deleted the folder and started the clone again. I edit the .env with python adding the API key and save it as .env, deleted the template and run again the script. All good

**Comment by ardventures** [comment]
I was able to get this to work by using Microsoft Visual Studio Code instead of TextEdit for modifying the .env file.

**Comment by GilesAlonso** [comment]
Installation instructions should be updated to include renaming the .env.template file through bash command, avoiding operating system interference on file association as I believe this to be the case.

**Comment by jennyqueenofswords** [comment]
IT WORKED! Had to delete the repo and re-clone but mv .env.template .env worked perfectly.

**Comment by drumstick90** [comment]
mv .env.template .env
from terminal worked here also!

**Comment by Lettte** [comment]
mv .env.template .env
worked！thx

**Comment by 21iridescent** [comment]
> Had the same problem. Had renamed .env.template in Finder. Just did mv .env.template .env and it worked. Which is weird as I had renamed the file in Finder.

Same here, I guessed the mac file system and the terminal file system are not aligned in some ways...

**Comment by dopesmope** [comment]
ok it seems like this has been resolved. Im like an average leve computer user, i dont know python. If anyone with a passion for teaching could break this down as much as possible i would appreciate it. im having the same issue. 

im copy/pasting the api key into the secrets tab for auto gpt , which i assumed was the entirety of the process. 
what is mv .env.template .env ? where do i put it? 
i promise if you extend mercy onto me by explaining this i will eventually learn python and teach some other poor soul, who is looking for an answer to their hyper specific problem. thank you

thank you

**Comment by ryderwishart** [comment]
I had this issue, saw the solutions, figured it was a permissions error, and indeed, it was a permissions error on the new file I had created (probably Mac making files prefixed with `.` inaccessible to the python script). 

To check if you have a permissions error, try running `sudo python -m autogpt`. Or, even more simply, compare the results of `ls` vs. `sudo ls`. If you don't see dot files when running `ls`, then it's likely a permission issue. 

At any rate, prefixing with `sudo` should get you up and running.
