### ISSUE TITLE
Another approach could be to run history through an embeddings API, save the embeddings to a Vector DB, then do a lookup for relevant _memories_ on each step.

### ISSUE THREAD

**Issue by KadirErturk4r** [Torantulino/Auto-GPT#89]
Another approach could be to run history through an embeddings API, save the embeddings to a Vector DB, then do a lookup for relevant _memories_ on each step.

_Originally posted by @tedspare in https://github.com/Torantulino/Auto-GPT/issues/5#issuecomment-1490464372_
            

That reminds me cross attention but in different context.

**Comment by jantic** [comment]
Any reason why this was closed? This is a great idea as far as I can tell....

**Comment by KadirErturk4r** [comment]
sorry it is my bad. I tried to add as a comment, but created a new issue.

**Comment by KadirErturk4r** [comment]
and also I wish you attach public models like GPT4All, so that we dont need GPT4
