### ISSUE TITLE
Installed everything correctly but its doesnt show the .env file? on mac

### ISSUE THREAD

**Issue by liop9** [Torantulino/Auto-GPT#891]

**Comment by Slowly-Grokking** [comment]
use the .env.template.  add your API keys etc, save as .env

**Comment by liop9** [comment]
I downloaded the file "Auto-GPT" it shows all the folders except ".env.template."

**Comment by dwrtz** [comment]
your operating system is probably hiding the files that begin with a dot. there should be a way to disable this behavior.

**Comment by arhyneRWU** [comment]
Hi, I got it running in less than 10 minutes and I'm a **biologist**  on a mac, ok to be fair I write a lot of code.  

I"m use PyCharm, cloned the git from there, everything shows up.  Makes life easier than command line. 

My guess is that you are you command line, you're likely not seeing it because it starts a "." 

You'll need to run the command in the terminal

ls -la

to see the .env.template or any other .filename

**Comment by liop9** [comment]
yes it worked i see the file ".env.template" but its faded and its a pages doc?

**Comment by dwrtz** [comment]
try `cp .env.template .env` to make a copy. then see if you can open .env in a text editor

**Comment by matthew-mw** [comment]
Try using ```command```+```shift```+```.```. This combo should do the trick!

**Comment by liop9** [comment]
it didnt work it still wont let me open?

**Comment by liop9** [comment]
it keeps saying the file format is invalid it their a reason for that?

**Comment by Slowly-Grokking** [comment]
Try editing .env  in terminal using nano.  or naming it env.txt  editing it, and then removing the .txt extension. 

https://support.apple.com/guide/terminal/use-command-line-text-editors-apdb02f1133-25af-4c65-8976-159609f99817/mac

**Comment by liop9** [comment]
it worked thanks homie

**Comment by ethanye77** [comment]
Are you looking to view hidden files in Finder? If so, you can hold down Command + Shift + .   keys to display the hidden files in the current folder. To hide them again, simply press the same key combination again.
<img width="777" alt="image" src="https://user-images.githubusercontent.com/128858378/231609082-132276c3-7ecc-448b-955a-a82284047e9f.png">
