### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'debug'

### ISSUE THREAD

**Issue by cuchorapido** [Torantulino/Auto-GPT#900]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I am just trying to run it like this:  `python scripts/main.py --continuous` and getting the following error:

```
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/opt/new/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/opt/new/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'
root@fe61f4ddfbe2:/opt/new/Auto-GPT#
```

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by nlile** [comment]
change `debug_mode` to `debug`

**Comment by mattbrown319** [comment]
Do you mean in config.py?   I'm getting the same error.

**Comment by StableInquest** [comment]
same error here

**Comment by nlile** [comment]
yep, in change `debug_mode` to `debug` or other way around. in `scripts/config.py`

**Comment by cuchorapido** [comment]
changing  `debug_mode` to `debug` in scripts/config.py worked!

**Comment by mattbrown319** [comment]
found another series of instances of debug_mode in json_utils.py.  it took a while for me to run into that error.  replaced "debug_mode" there with "debug" again.  Not sure if it fixed it...
