### ISSUE TITLE
Vinuca support?

### ISSUE THREAD

**Issue by jinfagang** [Torantulino/Auto-GPT#915]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We are so poor to using chatgpt tokens, does it support Vinuca?

### Motivation 🔦

We are so poor to using chatgpt tokens, does it support Vinuca?

**Comment by Timmytim1976** [comment]
Try: https://github.com/BillSchumacher/Auto-GPT/tree/vicuna

**Comment by hanskraut31312312** [comment]
Would be nice to expand the current version even and to help the poor folks. There should be 1 that is super lightweight for poor people with a bad pc 1 that is strong free model for people dont want to spend/experiement/poor with good pc and the normal openAI stuff

**Comment by jinfagang** [comment]
@Timmytim1976  hello, can u help write some readme instructions on how to run it?

**Comment by HustLion** [comment]
> @Timmytim1976 hello, can u help write some readme instructions on how to run it?

@jinfagang you can check out this instruction https://github.com/BillSchumacher/Auto-GPT/tree/vicuna#vicuna-local

**Comment by jinfagang** [comment]
@HustLion hello, how many GPU mem or mem needed to run Vicuna?

**Comment by richbeales** [comment]
closing due to presence of https://github.com/Torantulino/Auto-GPT/issues/567

**Comment by HustLion** [comment]
I'm able to run it with 10G VRAM (Nvidia rtx 3080).  It also supports pure CPU mode.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/12/2023 19:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Torantulino/Auto-GPT] Vinuca support? (Issue #915) |

@HustLion hello, how many GPU mem or mem needed to run Vicuna?
