### ISSUE TITLE
'Config' object has no attribute 'debug' while running main.py

### ISSUE THREAD

**Issue by samueli** [Torantulino/Auto-GPT#937]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

just running main.py

### Current behavior 😯

Traceback (most recent call last):
  File "/Users/xxx/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'

### Your prompt 📝

Remove ```# TODO: Change debug from hardcode to argument``` in file: scripts/chat.py
And change ```if cfg.debug``` to ```if cfg.debug_mode```

**Comment by richbeales** [comment]
Please pull latest code from git (git pull)

**Comment by samueli** [comment]
> 

ok, thanks
