### ISSUE TITLE
main.python cant be found or crashes when started.

### ISSUE THREAD

**Issue by ImaTheWorstCoderEver** [Torantulino/Auto-GPT#962]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

in cmd console useing command python scripts/main.py comes back with error 2 file not found. 

### Current behavior 😯

When useing cmd python scripts/main.py to start Auto-GBT it says the the file can not be found. Going to the files location and starting it leads to an instant crash

### Expected behavior 🤔

When useing python scripts/main.py or clicking on file Auto-GBT should start. IT DOES NOT

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by metacubic** [comment]
You need to run with administrator privileges

**Comment by metacubic** [comment]
![image](https://user-images.githubusercontent.com/95690201/231502522-90701449-a46a-4141-9d3e-1c73df5bec7b.png)

Other issues after, just add that line into config.py

**Comment by p-i-** [comment]
PEBCAK
Discord is good for basic help.
Closing issue as it's not clearly stated, and doesn't give devs anything to work with.

**Comment by ImaTheWorstCoderEver** [comment]
> You need to run with administrator privileges

How do I run as admin
