### ISSUE TITLE
Api Rate Limit

### ISSUE THREAD

**Issue by metacubic** [Torantulino/Auto-GPT#966]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Runing the agent after config.py was edited

### Current behavior 😯

Error: API Rate Limit Reached

### Expected behavior 🤔

There is no rate limit reached, as I've checked and I'm still on 0.

![image](https://user-images.githubusercontent.com/95690201/231507322-b70a8052-37d1-4326-921d-0ea3026d2826.png)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by crowtechAI** [comment]
Your free credit has an expiration data and it has been reached, this shows your free credit has expired and either you add a payment method or create another account with a new valid phone number

**Comment by metacubic** [comment]
https://github.com/Torantulino/Auto-GPT/issues/75

Yes read the issues here, there was no credits issued under the 'Free Account', as it was a 'Brand New Account'.

I can confirm, that they are restricting to 'Paid Accounts' only it would seem.
