### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'debug'

### ISSUE THREAD

**Issue by mindxfuture** [Torantulino/Auto-GPT#967]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Hi
I have finished the previous settings for GPT name and 5 Goals together normally. But when I finish continue （y/n）: I selected Y, then I get this Error Prompt

### Your prompt 📝

```yaml
# Using memory of type: LocalCache
Traceback (most recent call last):
  File "D:\LearningAI\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "D:\LearningAI\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'
```

**Comment by slaguru666** [comment]
Getting this as well. Interested to know what I have done wrong

**Comment by DerekCL** [comment]
there was a pr that was merged recently to fix these errors and I'm using the head for master

commit 16b37fff1d65a7d998c39aeab9764973d76ea731 (HEAD -> master, tag: v0.1.0, origin/master, origin/HEAD)
Author: sarango <sarango@swiset.com>
Date:   Mon Apr 10 08:07:03 2023 -0500

I cannot replicate your error as my code runs fine 

             /////////////                gitderekt@pop-os 
         /////////////////////            ---------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Kernel: 6.2.6-76060206-generic 
   /////76767//7676767//////////////      Uptime: 11 hours, 47 mins 
  /////767676///*76767///////////////     Packages: 2001 (dpkg), 11 (flatpak),  
 ///////767676///76767.///7676*///////    Shell: zsh 5.8.1 
/////////767676//76767///767676////////   Resolution: 1920x1080, 1920x1080, 192 
//////////76767676767////76767/////////   DE: GNOME 42.5 
///////////76767676//////7676//////////   WM: Mutter 
////////////,7676,///////767///////////   WM Theme: Pop 
/////////////*7676///////76////////////   Theme: Pop-dark [GTK2/3] 
///////////////7676////////////////////   Icons: Pop [GTK2/3] 
 ///////////////7676///767////////////    Terminal: gnome-terminal 
  //////////////////////'////////////     CPU: AMD Ryzen 9 5900X (24) @ 3.700GH 
   //////.7676767676767676767,//////      GPU: NVIDIA 0c:00.0 NVIDIA Corporatio 
    /////767676767676767676767/////       Memory: 11531MiB / 64198MiB 
      ///////////////////////////
         /////////////////////                                    
             /////////////

**Comment by slaguru666** [comment]
That worked, thanks

**Comment by mattedwardseo** [comment]
I'm still having this issue. I'm sorry I'm new to any of this. I managed to fetch and pull new version (or so I think) but I am still having the same issue. I tried all previous fixes and noticed that changes were implemented when I pulled the new version. But it still gives me the error: PS C:\Users\mattb\Auto-GPT> py scripts/main.py
Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings?
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth', 'Grow Twitter Account', 'Develop and manage multiple businesses autonomously']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "C:\Users\mattb\Auto-GPT\scripts\main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mattb\Auto-GPT\scripts\chat.py", line 67, in chat_with_ai
    if cfg.debug:
       ^^^^^^^^^
AttributeError: 'Config' object has no attribute 'debug'
PS C:\Users\mattb\Auto-GPT>

I don't really know this stuff but I don't see any other options for fixing this. Do I just need to uninstall everything and try again? Or am I maybe doing something wrong? Sorry if duplicate issue but I searched all the other threads and tried everything I think.

**Comment by hellohau** [comment]
You can try changing cfg.debug to -> cfg.debug_mode

**Comment by hellohau** [comment]
Also I think the latest commits fix these bugs

**Comment by p-i-** [comment]
Look in master branch at the referenced line (67):
https://github.com/Torantulino/Auto-GPT/blob/master/scripts/chat.py#L67

You'll see that this line doesn't match yours.
So you are running out-of-date source-code.

Closing this for now.
