### ISSUE TITLE
name 'sk' is not defined

### ISSUE THREAD

**Issue by diizy-bit** [Torantulino/Auto-GPT#973]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Set up everything as normal and then change the config.py file to have your API key in it aswell as change the env file to have the same API key in it.

### Current behavior 😯

When I try to run the command  "python3 scripts/main.py" I get this message returned with the problem being down at the end of the message where it says name 'sk' is not defined
<img width="1084" alt="Screenshot 2023-04-12 at 12 05 35 PM" src="https://user-images.githubusercontent.com/121648511/231516965-e1886b47-0e1b-407a-9884-89574e9e110b.png">

### Expected behavior 🤔

What should happen is I get to use autogpt without this issue

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by SanketPatole** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Steps to reproduce 🕹
> Set up everything as normal and then change the config.py file to have your API key in it aswell as change the env file to have the same API key in it.
> 
> ### Current behavior 😯
> When I try to run the command "python3 scripts/main.py" I get this message returned with the problem being down at the end of the message where it says name 'sk' is not defined <img alt="Screenshot 2023-04-12 at 12 05 35 PM" width="1084" src="https://user-images.githubusercontent.com/121648511/231516965-e1886b47-0e1b-407a-9884-89574e9e110b.png">
> 
> ### Expected behavior 🤔
> What should happen is I get to use autogpt without this issue
> 
> ### Your prompt 📝
> ```yaml
> # Paste your prompt here
> ```

Open scripts/config.py

Does your line 45 look like this?

![image](https://user-images.githubusercontent.com/69233883/231522813-d004643a-7e85-459e-9218-5895d0143db2.png)

**Comment by diizy-bit** [comment]
No I have pasted my API key in there. The API key starts with sk- so I assume its something with that.

**Comment by SanketPatole** [comment]
> No I have pasted my API key in there. The API key starts with sk- so I assume its something with that.

Actually that line checks for an environment variable named, OPENAI_API_KEY.
Also, you have directly pasted the key without quotes, so it's assuming to be a variable or identifier.
Was it mentioned anywhere to update config.py file too?
If not, please keep key values in .env file. but revert the changes to config.py file and try again.

**Comment by diizy-bit** [comment]
I am on a mac if that changes anything. It was mentioned to update that file. It said to update that or to change the ENV file and the ENV file did not seem to work so I tried changing this also. I will try hardcoding it as you mentioned and see what happens

**Comment by diizy-bit** [comment]
I hard coded it and now it works thank you!

**Comment by JasonKitman** [comment]
I had the same error and this worked for me too. Thank you!
