### ISSUE TITLE
Long Term Memory Should be Open Source, Weaviate et al.

### ISSUE THREAD

**Issue by MarcusSorealheis** [Torantulino/Auto-GPT#976]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

One of the most frustrating characteristics of LLMs and the corpora which form their bases is the bias and prejudice of the past that we’d like to forget. The implications of bringing too much of it forward is very risky. For some users, it could me damage to brand reputation and lower revenue, for others it could mean an adverse chemical reaction yielding a dangerous medication. I believe the memory system (a vector database) ought to be based on open source technology to facilitate introspection and their ability to move the brain should it need to be protected. Weaviate and QDrant would both be fine, though the first would give more capabilities. I am willing to sponsor. 

### Examples 🌈

What is retrieved and stored from the web. Can we evaluate it? Has it been altered. Can we reproduce the same behavior consistently locally, or in an air-gapped environment?

### Motivation 🔦

Safety, security, and our species. As I said, I am happy to sponsor, for my family’s sake.

**Comment by cryptidv** [comment]
Absolutely I 100% agree, but that doesn't mean we shouldn't implement closed-source solutions. Freedom of choice is just as important.

**Comment by p-i-** [comment]
If you look at what Pinecone is doing at a technical level, it is just storing a large array of `context-vectors`. You feed in a new `context-vector` and it will return the k nearest neighbours.

You can test this out yourself, and compare the pinecone solution with our local-memory solution. If you examine that file you'll see it's about 5 lines of code.

There's no point in demanding an open-source alternative to Pinecone -- if your concern is transparency, your focus is better directed at the data with which the LLM is trained. That's the mountain; pinecone is not even a molehill.
