### ISSUE TITLE
.env.template is missing

### ISSUE THREAD

**Issue by drumstick90** [Torantulino/Auto-GPT#996]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

After following along up to Step 4, 
.env.template sems to be missing

<img width="939" alt="Screenshot 2023-04-12 at 20 56 47" src="https://user-images.githubusercontent.com/43449169/231557605-f716c44c-1b9b-453a-b9fd-9f98af510465.png">

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by p-i-** [comment]
Ah, it might be that your file-viewer is hiding dot-files. Any file/folder that starts with `.` is considered a system-file.

It's always best to work from the CLI.

Alternatively you can find a setting in your file-viewer to show dot/hidden/system files.

**Comment by drumstick90** [comment]
Thank you. Indeed on OSX go to folder and press cmd+shift+.
